// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=repository_mock.go -package=storage
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/Haerd-Limited/dating-api/internal/compatibility/domain"
	entity "github.com/Haerd-Limited/dating-api/internal/entity"
)

// MockCompatibilityRepository is a mock of CompatibilityRepository interface.
type MockCompatibilityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCompatibilityRepositoryMockRecorder
	isgomock struct{}
}

// MockCompatibilityRepositoryMockRecorder is the mock recorder for MockCompatibilityRepository.
type MockCompatibilityRepositoryMockRecorder struct {
	mock *MockCompatibilityRepository
}

// NewMockCompatibilityRepository creates a new mock instance.
func NewMockCompatibilityRepository(ctrl *gomock.Controller) *MockCompatibilityRepository {
	mock := &MockCompatibilityRepository{ctrl: ctrl}
	mock.recorder = &MockCompatibilityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompatibilityRepository) EXPECT() *MockCompatibilityRepositoryMockRecorder {
	return m.recorder
}

// CompatibilityHighlights mocks base method.
func (m *MockCompatibilityRepository) CompatibilityHighlights(ctx context.Context, viewerID, targetID string, limit int) ([]domain.CompatibilityHighlight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompatibilityHighlights", ctx, viewerID, targetID, limit)
	ret0, _ := ret[0].([]domain.CompatibilityHighlight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompatibilityHighlights indicates an expected call of CompatibilityHighlights.
func (mr *MockCompatibilityRepositoryMockRecorder) CompatibilityHighlights(ctx, viewerID, targetID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompatibilityHighlights", reflect.TypeOf((*MockCompatibilityRepository)(nil).CompatibilityHighlights), ctx, viewerID, targetID, limit)
}

// CountAnsweredByCategory mocks base method.
func (m *MockCompatibilityRepository) CountAnsweredByCategory(ctx context.Context, userID, categoryKey string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAnsweredByCategory", ctx, userID, categoryKey)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAnsweredByCategory indicates an expected call of CountAnsweredByCategory.
func (mr *MockCompatibilityRepositoryMockRecorder) CountAnsweredByCategory(ctx, userID, categoryKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAnsweredByCategory", reflect.TypeOf((*MockCompatibilityRepository)(nil).CountAnsweredByCategory), ctx, userID, categoryKey)
}

// CountQuestions mocks base method.
func (m *MockCompatibilityRepository) CountQuestions(ctx context.Context, categoryKey *string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountQuestions", ctx, categoryKey)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountQuestions indicates an expected call of CountQuestions.
func (mr *MockCompatibilityRepositoryMockRecorder) CountQuestions(ctx, categoryKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountQuestions", reflect.TypeOf((*MockCompatibilityRepository)(nil).CountQuestions), ctx, categoryKey)
}

// CountUserAnswers mocks base method.
func (m *MockCompatibilityRepository) CountUserAnswers(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserAnswers", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserAnswers indicates an expected call of CountUserAnswers.
func (mr *MockCompatibilityRepositoryMockRecorder) CountUserAnswers(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserAnswers", reflect.TypeOf((*MockCompatibilityRepository)(nil).CountUserAnswers), ctx, userID)
}

// GetAnswerIDsForQuestion mocks base method.
func (m *MockCompatibilityRepository) GetAnswerIDsForQuestion(ctx context.Context, questionID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnswerIDsForQuestion", ctx, questionID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnswerIDsForQuestion indicates an expected call of GetAnswerIDsForQuestion.
func (mr *MockCompatibilityRepositoryMockRecorder) GetAnswerIDsForQuestion(ctx, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnswerIDsForQuestion", reflect.TypeOf((*MockCompatibilityRepository)(nil).GetAnswerIDsForQuestion), ctx, questionID)
}

// GetNextUnansweredQuestion mocks base method.
func (m *MockCompatibilityRepository) GetNextUnansweredQuestion(ctx context.Context, userID, categoryKey string) (*entity.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextUnansweredQuestion", ctx, userID, categoryKey)
	ret0, _ := ret[0].(*entity.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextUnansweredQuestion indicates an expected call of GetNextUnansweredQuestion.
func (mr *MockCompatibilityRepositoryMockRecorder) GetNextUnansweredQuestion(ctx, userID, categoryKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextUnansweredQuestion", reflect.TypeOf((*MockCompatibilityRepository)(nil).GetNextUnansweredQuestion), ctx, userID, categoryKey)
}

// GetQuestionAnswers mocks base method.
func (m *MockCompatibilityRepository) GetQuestionAnswers(ctx context.Context, questionID int64) (entity.QuestionAnswerSlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionAnswers", ctx, questionID)
	ret0, _ := ret[0].(entity.QuestionAnswerSlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionAnswers indicates an expected call of GetQuestionAnswers.
func (mr *MockCompatibilityRepositoryMockRecorder) GetQuestionAnswers(ctx, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionAnswers", reflect.TypeOf((*MockCompatibilityRepository)(nil).GetQuestionAnswers), ctx, questionID)
}

// GetQuestionByIDAndCategory mocks base method.
func (m *MockCompatibilityRepository) GetQuestionByIDAndCategory(ctx context.Context, questionID int64, categoryKey string) (*entity.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionByIDAndCategory", ctx, questionID, categoryKey)
	ret0, _ := ret[0].(*entity.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionByIDAndCategory indicates an expected call of GetQuestionByIDAndCategory.
func (mr *MockCompatibilityRepositoryMockRecorder) GetQuestionByIDAndCategory(ctx, questionID, categoryKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionByIDAndCategory", reflect.TypeOf((*MockCompatibilityRepository)(nil).GetQuestionByIDAndCategory), ctx, questionID, categoryKey)
}

// GetQuestionCategories mocks base method.
func (m *MockCompatibilityRepository) GetQuestionCategories(ctx context.Context) (entity.QuestionCategorySlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionCategories", ctx)
	ret0, _ := ret[0].(entity.QuestionCategorySlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionCategories indicates an expected call of GetQuestionCategories.
func (mr *MockCompatibilityRepositoryMockRecorder) GetQuestionCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionCategories", reflect.TypeOf((*MockCompatibilityRepository)(nil).GetQuestionCategories), ctx)
}

// GetQuestionSortOrderAndCategory mocks base method.
func (m *MockCompatibilityRepository) GetQuestionSortOrderAndCategory(ctx context.Context, questionID int64) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionSortOrderAndCategory", ctx, questionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetQuestionSortOrderAndCategory indicates an expected call of GetQuestionSortOrderAndCategory.
func (mr *MockCompatibilityRepositoryMockRecorder) GetQuestionSortOrderAndCategory(ctx, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionSortOrderAndCategory", reflect.TypeOf((*MockCompatibilityRepository)(nil).GetQuestionSortOrderAndCategory), ctx, questionID)
}

// GetQuestionsInOrder mocks base method.
func (m *MockCompatibilityRepository) GetQuestionsInOrder(ctx context.Context, categoryKey string) (entity.QuestionSlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionsInOrder", ctx, categoryKey)
	ret0, _ := ret[0].(entity.QuestionSlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionsInOrder indicates an expected call of GetQuestionsInOrder.
func (mr *MockCompatibilityRepositoryMockRecorder) GetQuestionsInOrder(ctx, categoryKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionsInOrder", reflect.TypeOf((*MockCompatibilityRepository)(nil).GetQuestionsInOrder), ctx, categoryKey)
}

// GetUserAnswerForQuestion mocks base method.
func (m *MockCompatibilityRepository) GetUserAnswerForQuestion(ctx context.Context, userID string, questionID int64) (*entity.UserAnswer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAnswerForQuestion", ctx, userID, questionID)
	ret0, _ := ret[0].(*entity.UserAnswer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAnswerForQuestion indicates an expected call of GetUserAnswerForQuestion.
func (mr *MockCompatibilityRepositoryMockRecorder) GetUserAnswerForQuestion(ctx, userID, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAnswerForQuestion", reflect.TypeOf((*MockCompatibilityRepository)(nil).GetUserAnswerForQuestion), ctx, userID, questionID)
}

// GetUserAnsweredQuestionIDs mocks base method.
func (m *MockCompatibilityRepository) GetUserAnsweredQuestionIDs(ctx context.Context, userID, categoryKey string) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAnsweredQuestionIDs", ctx, userID, categoryKey)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAnsweredQuestionIDs indicates an expected call of GetUserAnsweredQuestionIDs.
func (mr *MockCompatibilityRepositoryMockRecorder) GetUserAnsweredQuestionIDs(ctx, userID, categoryKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAnsweredQuestionIDs", reflect.TypeOf((*MockCompatibilityRepository)(nil).GetUserAnsweredQuestionIDs), ctx, userID, categoryKey)
}

// GetUserAnswers mocks base method.
func (m *MockCompatibilityRepository) GetUserAnswers(ctx context.Context, userID string) (entity.UserAnswerSlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAnswers", ctx, userID)
	ret0, _ := ret[0].(entity.UserAnswerSlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAnswers indicates an expected call of GetUserAnswers.
func (mr *MockCompatibilityRepositoryMockRecorder) GetUserAnswers(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAnswers", reflect.TypeOf((*MockCompatibilityRepository)(nil).GetUserAnswers), ctx, userID)
}

// HasMandatoryMismatch mocks base method.
func (m *MockCompatibilityRepository) HasMandatoryMismatch(ctx context.Context, aID, bID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasMandatoryMismatch", ctx, aID, bID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasMandatoryMismatch indicates an expected call of HasMandatoryMismatch.
func (mr *MockCompatibilityRepositoryMockRecorder) HasMandatoryMismatch(ctx, aID, bID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMandatoryMismatch", reflect.TypeOf((*MockCompatibilityRepository)(nil).HasMandatoryMismatch), ctx, aID, bID)
}

// ListQuestions mocks base method.
func (m *MockCompatibilityRepository) ListQuestions(ctx context.Context, categoryKey *string, limit, offset int) (entity.QuestionSlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQuestions", ctx, categoryKey, limit, offset)
	ret0, _ := ret[0].(entity.QuestionSlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQuestions indicates an expected call of ListQuestions.
func (mr *MockCompatibilityRepositoryMockRecorder) ListQuestions(ctx, categoryKey, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQuestions", reflect.TypeOf((*MockCompatibilityRepository)(nil).ListQuestions), ctx, categoryKey, limit, offset)
}

// MandatoryMismatchBadges mocks base method.
func (m *MockCompatibilityRepository) MandatoryMismatchBadges(ctx context.Context, viewerID, targetID string, limit int) ([]domain.CompatibilityBadge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MandatoryMismatchBadges", ctx, viewerID, targetID, limit)
	ret0, _ := ret[0].([]domain.CompatibilityBadge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MandatoryMismatchBadges indicates an expected call of MandatoryMismatchBadges.
func (mr *MockCompatibilityRepositoryMockRecorder) MandatoryMismatchBadges(ctx, viewerID, targetID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MandatoryMismatchBadges", reflect.TypeOf((*MockCompatibilityRepository)(nil).MandatoryMismatchBadges), ctx, viewerID, targetID, limit)
}

// PerspectiveSums mocks base method.
func (m *MockCompatibilityRepository) PerspectiveSums(ctx context.Context, aID, bID string) (int, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerspectiveSums", ctx, aID, bID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// PerspectiveSums indicates an expected call of PerspectiveSums.
func (mr *MockCompatibilityRepositoryMockRecorder) PerspectiveSums(ctx, aID, bID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerspectiveSums", reflect.TypeOf((*MockCompatibilityRepository)(nil).PerspectiveSums), ctx, aID, bID)
}

// PerspectiveSumsByCategory mocks base method.
func (m *MockCompatibilityRepository) PerspectiveSumsByCategory(ctx context.Context, aID, bID, categoryKey string) (int, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerspectiveSumsByCategory", ctx, aID, bID, categoryKey)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// PerspectiveSumsByCategory indicates an expected call of PerspectiveSumsByCategory.
func (mr *MockCompatibilityRepositoryMockRecorder) PerspectiveSumsByCategory(ctx, aID, bID, categoryKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerspectiveSumsByCategory", reflect.TypeOf((*MockCompatibilityRepository)(nil).PerspectiveSumsByCategory), ctx, aID, bID, categoryKey)
}

// TopBadges mocks base method.
func (m *MockCompatibilityRepository) TopBadges(ctx context.Context, aID, bID string, limit int) ([]domain.CompatibilityBadge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopBadges", ctx, aID, bID, limit)
	ret0, _ := ret[0].([]domain.CompatibilityBadge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopBadges indicates an expected call of TopBadges.
func (mr *MockCompatibilityRepositoryMockRecorder) TopBadges(ctx, aID, bID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopBadges", reflect.TypeOf((*MockCompatibilityRepository)(nil).TopBadges), ctx, aID, bID, limit)
}

// UpsertUserAnswer mocks base method.
func (m *MockCompatibilityRepository) UpsertUserAnswer(ctx context.Context, answer entity.UserAnswer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserAnswer", ctx, answer)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserAnswer indicates an expected call of UpsertUserAnswer.
func (mr *MockCompatibilityRepositoryMockRecorder) UpsertUserAnswer(ctx, answer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserAnswer", reflect.TypeOf((*MockCompatibilityRepository)(nil).UpsertUserAnswer), ctx, answer)
}
