// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"strconv"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// M type is for providing columns and column values to UpdateAll.
type M map[string]interface{}

// ErrSyncFail occurs during insert when the record could not be retrieved in
// order to populate default value information. This usually happens when LastInsertId
// fails or there was a primary key configuration that was not resolvable.
var ErrSyncFail = errors.New("entity: failed to synchronize data after insert")

type insertCache struct {
	query        string
	retQuery     string
	valueMapping []uint64
	retMapping   []uint64
}

type updateCache struct {
	query        string
	valueMapping []uint64
}

func makeCacheKey(cols boil.Columns, nzDefaults []string) string {
	buf := strmangle.GetBuffer()

	buf.WriteString(strconv.Itoa(cols.Kind))
	for _, w := range cols.Cols {
		buf.WriteString(w)
	}

	if len(nzDefaults) != 0 {
		buf.WriteByte('.')
	}
	for _, nz := range nzDefaults {
		buf.WriteString(nz)
	}

	str := buf.String()
	strmangle.PutBuffer(buf)
	return str
}

// Enum values for MatchStatus
const (
	MatchStatusActive    string = "active"
	MatchStatusUnmatched string = "unmatched"
	MatchStatusBlocked   string = "blocked"
)

func AllMatchStatus() []string {
	return []string{
		MatchStatusActive,
		MatchStatusUnmatched,
		MatchStatusBlocked,
	}
}

// Enum values for MessageType
const (
	MessageTypeText   string = "text"
	MessageTypeVoice  string = "voice"
	MessageTypeSystem string = "system"
)

func AllMessageType() []string {
	return []string{
		MessageTypeText,
		MessageTypeVoice,
		MessageTypeSystem,
	}
}

// Enum values for VisibilityLevel
const (
	VisibilityLevelHidden        string = "hidden"
	VisibilityLevelVisible       string = "visible"
	VisibilityLevelAlwaysHidden  string = "always_hidden"
	VisibilityLevelAlwaysVisible string = "always_visible"
)

func AllVisibilityLevel() []string {
	return []string{
		VisibilityLevelHidden,
		VisibilityLevelVisible,
		VisibilityLevelAlwaysHidden,
		VisibilityLevelAlwaysVisible,
	}
}
