// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// DatingIntention is an object representing the database table.
type DatingIntention struct {
	ID    int16  `boil:"id" json:"id" toml:"id" yaml:"id"`
	Label string `boil:"label" json:"label" toml:"label" yaml:"label"`

	R *datingIntentionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L datingIntentionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DatingIntentionColumns = struct {
	ID    string
	Label string
}{
	ID:    "id",
	Label: "label",
}

var DatingIntentionTableColumns = struct {
	ID    string
	Label string
}{
	ID:    "dating_intentions.id",
	Label: "dating_intentions.label",
}

// Generated where

type whereHelperint16 struct{ field string }

func (w whereHelperint16) EQ(x int16) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint16) NEQ(x int16) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint16) LT(x int16) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint16) LTE(x int16) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint16) GT(x int16) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint16) GTE(x int16) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint16) IN(slice []int16) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint16) NIN(slice []int16) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var DatingIntentionWhere = struct {
	ID    whereHelperint16
	Label whereHelperstring
}{
	ID:    whereHelperint16{field: "\"dating_intentions\".\"id\""},
	Label: whereHelperstring{field: "\"dating_intentions\".\"label\""},
}

// DatingIntentionRels is where relationship names are stored.
var DatingIntentionRels = struct {
	UserProfiles string
}{
	UserProfiles: "UserProfiles",
}

// datingIntentionR is where relationships are stored.
type datingIntentionR struct {
	UserProfiles UserProfileSlice `boil:"UserProfiles" json:"UserProfiles" toml:"UserProfiles" yaml:"UserProfiles"`
}

// NewStruct creates a new relationship struct
func (*datingIntentionR) NewStruct() *datingIntentionR {
	return &datingIntentionR{}
}

func (o *DatingIntention) GetUserProfiles() UserProfileSlice {
	if o == nil {
		return nil
	}

	return o.R.GetUserProfiles()
}

func (r *datingIntentionR) GetUserProfiles() UserProfileSlice {
	if r == nil {
		return nil
	}

	return r.UserProfiles
}

// datingIntentionL is where Load methods for each relationship are stored.
type datingIntentionL struct{}

var (
	datingIntentionAllColumns            = []string{"id", "label"}
	datingIntentionColumnsWithoutDefault = []string{"label"}
	datingIntentionColumnsWithDefault    = []string{"id"}
	datingIntentionPrimaryKeyColumns     = []string{"id"}
	datingIntentionGeneratedColumns      = []string{}
)

type (
	// DatingIntentionSlice is an alias for a slice of pointers to DatingIntention.
	// This should almost always be used instead of []DatingIntention.
	DatingIntentionSlice []*DatingIntention
	// DatingIntentionHook is the signature for custom DatingIntention hook methods
	DatingIntentionHook func(context.Context, boil.ContextExecutor, *DatingIntention) error

	datingIntentionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	datingIntentionType                 = reflect.TypeOf(&DatingIntention{})
	datingIntentionMapping              = queries.MakeStructMapping(datingIntentionType)
	datingIntentionPrimaryKeyMapping, _ = queries.BindMapping(datingIntentionType, datingIntentionMapping, datingIntentionPrimaryKeyColumns)
	datingIntentionInsertCacheMut       sync.RWMutex
	datingIntentionInsertCache          = make(map[string]insertCache)
	datingIntentionUpdateCacheMut       sync.RWMutex
	datingIntentionUpdateCache          = make(map[string]updateCache)
	datingIntentionUpsertCacheMut       sync.RWMutex
	datingIntentionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var datingIntentionAfterSelectMu sync.Mutex
var datingIntentionAfterSelectHooks []DatingIntentionHook

var datingIntentionBeforeInsertMu sync.Mutex
var datingIntentionBeforeInsertHooks []DatingIntentionHook
var datingIntentionAfterInsertMu sync.Mutex
var datingIntentionAfterInsertHooks []DatingIntentionHook

var datingIntentionBeforeUpdateMu sync.Mutex
var datingIntentionBeforeUpdateHooks []DatingIntentionHook
var datingIntentionAfterUpdateMu sync.Mutex
var datingIntentionAfterUpdateHooks []DatingIntentionHook

var datingIntentionBeforeDeleteMu sync.Mutex
var datingIntentionBeforeDeleteHooks []DatingIntentionHook
var datingIntentionAfterDeleteMu sync.Mutex
var datingIntentionAfterDeleteHooks []DatingIntentionHook

var datingIntentionBeforeUpsertMu sync.Mutex
var datingIntentionBeforeUpsertHooks []DatingIntentionHook
var datingIntentionAfterUpsertMu sync.Mutex
var datingIntentionAfterUpsertHooks []DatingIntentionHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DatingIntention) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datingIntentionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DatingIntention) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datingIntentionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DatingIntention) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datingIntentionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DatingIntention) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datingIntentionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DatingIntention) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datingIntentionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DatingIntention) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datingIntentionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DatingIntention) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datingIntentionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DatingIntention) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datingIntentionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DatingIntention) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datingIntentionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDatingIntentionHook registers your hook function for all future operations.
func AddDatingIntentionHook(hookPoint boil.HookPoint, datingIntentionHook DatingIntentionHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		datingIntentionAfterSelectMu.Lock()
		datingIntentionAfterSelectHooks = append(datingIntentionAfterSelectHooks, datingIntentionHook)
		datingIntentionAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		datingIntentionBeforeInsertMu.Lock()
		datingIntentionBeforeInsertHooks = append(datingIntentionBeforeInsertHooks, datingIntentionHook)
		datingIntentionBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		datingIntentionAfterInsertMu.Lock()
		datingIntentionAfterInsertHooks = append(datingIntentionAfterInsertHooks, datingIntentionHook)
		datingIntentionAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		datingIntentionBeforeUpdateMu.Lock()
		datingIntentionBeforeUpdateHooks = append(datingIntentionBeforeUpdateHooks, datingIntentionHook)
		datingIntentionBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		datingIntentionAfterUpdateMu.Lock()
		datingIntentionAfterUpdateHooks = append(datingIntentionAfterUpdateHooks, datingIntentionHook)
		datingIntentionAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		datingIntentionBeforeDeleteMu.Lock()
		datingIntentionBeforeDeleteHooks = append(datingIntentionBeforeDeleteHooks, datingIntentionHook)
		datingIntentionBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		datingIntentionAfterDeleteMu.Lock()
		datingIntentionAfterDeleteHooks = append(datingIntentionAfterDeleteHooks, datingIntentionHook)
		datingIntentionAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		datingIntentionBeforeUpsertMu.Lock()
		datingIntentionBeforeUpsertHooks = append(datingIntentionBeforeUpsertHooks, datingIntentionHook)
		datingIntentionBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		datingIntentionAfterUpsertMu.Lock()
		datingIntentionAfterUpsertHooks = append(datingIntentionAfterUpsertHooks, datingIntentionHook)
		datingIntentionAfterUpsertMu.Unlock()
	}
}

// One returns a single datingIntention record from the query.
func (q datingIntentionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DatingIntention, error) {
	o := &DatingIntention{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: failed to execute a one query for dating_intentions")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DatingIntention records from the query.
func (q datingIntentionQuery) All(ctx context.Context, exec boil.ContextExecutor) (DatingIntentionSlice, error) {
	var o []*DatingIntention

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "entity: failed to assign all query results to DatingIntention slice")
	}

	if len(datingIntentionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DatingIntention records in the query.
func (q datingIntentionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to count dating_intentions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q datingIntentionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "entity: failed to check if dating_intentions exists")
	}

	return count > 0, nil
}

// UserProfiles retrieves all the user_profile's UserProfiles with an executor.
func (o *DatingIntention) UserProfiles(mods ...qm.QueryMod) userProfileQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"user_profiles\".\"dating_intention_id\"=?", o.ID),
	)

	return UserProfiles(queryMods...)
}

// LoadUserProfiles allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (datingIntentionL) LoadUserProfiles(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDatingIntention interface{}, mods queries.Applicator) error {
	var slice []*DatingIntention
	var object *DatingIntention

	if singular {
		var ok bool
		object, ok = maybeDatingIntention.(*DatingIntention)
		if !ok {
			object = new(DatingIntention)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDatingIntention)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDatingIntention))
			}
		}
	} else {
		s, ok := maybeDatingIntention.(*[]*DatingIntention)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDatingIntention)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDatingIntention))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &datingIntentionR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &datingIntentionR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`user_profiles`),
		qm.WhereIn(`user_profiles.dating_intention_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load user_profiles")
	}

	var resultSlice []*UserProfile
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice user_profiles")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on user_profiles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user_profiles")
	}

	if len(userProfileAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.UserProfiles = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &userProfileR{}
			}
			foreign.R.DatingIntention = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.DatingIntentionID) {
				local.R.UserProfiles = append(local.R.UserProfiles, foreign)
				if foreign.R == nil {
					foreign.R = &userProfileR{}
				}
				foreign.R.DatingIntention = local
				break
			}
		}
	}

	return nil
}

// AddUserProfiles adds the given related objects to the existing relationships
// of the dating_intention, optionally inserting them as new records.
// Appends related to o.R.UserProfiles.
// Sets related.R.DatingIntention appropriately.
func (o *DatingIntention) AddUserProfiles(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*UserProfile) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.DatingIntentionID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"user_profiles\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"dating_intention_id"}),
				strmangle.WhereClause("\"", "\"", 2, userProfilePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.UserID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.DatingIntentionID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &datingIntentionR{
			UserProfiles: related,
		}
	} else {
		o.R.UserProfiles = append(o.R.UserProfiles, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &userProfileR{
				DatingIntention: o,
			}
		} else {
			rel.R.DatingIntention = o
		}
	}
	return nil
}

// SetUserProfiles removes all previously related items of the
// dating_intention replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.DatingIntention's UserProfiles accordingly.
// Replaces o.R.UserProfiles with related.
// Sets related.R.DatingIntention's UserProfiles accordingly.
func (o *DatingIntention) SetUserProfiles(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*UserProfile) error {
	query := "update \"user_profiles\" set \"dating_intention_id\" = null where \"dating_intention_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.UserProfiles {
			queries.SetScanner(&rel.DatingIntentionID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.DatingIntention = nil
		}
		o.R.UserProfiles = nil
	}

	return o.AddUserProfiles(ctx, exec, insert, related...)
}

// RemoveUserProfiles relationships from objects passed in.
// Removes related items from R.UserProfiles (uses pointer comparison, removal does not keep order)
// Sets related.R.DatingIntention.
func (o *DatingIntention) RemoveUserProfiles(ctx context.Context, exec boil.ContextExecutor, related ...*UserProfile) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.DatingIntentionID, nil)
		if rel.R != nil {
			rel.R.DatingIntention = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("dating_intention_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.UserProfiles {
			if rel != ri {
				continue
			}

			ln := len(o.R.UserProfiles)
			if ln > 1 && i < ln-1 {
				o.R.UserProfiles[i] = o.R.UserProfiles[ln-1]
			}
			o.R.UserProfiles = o.R.UserProfiles[:ln-1]
			break
		}
	}

	return nil
}

// DatingIntentions retrieves all the records using an executor.
func DatingIntentions(mods ...qm.QueryMod) datingIntentionQuery {
	mods = append(mods, qm.From("\"dating_intentions\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"dating_intentions\".*"})
	}

	return datingIntentionQuery{q}
}

// FindDatingIntention retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDatingIntention(ctx context.Context, exec boil.ContextExecutor, iD int16, selectCols ...string) (*DatingIntention, error) {
	datingIntentionObj := &DatingIntention{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"dating_intentions\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, datingIntentionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: unable to select from dating_intentions")
	}

	if err = datingIntentionObj.doAfterSelectHooks(ctx, exec); err != nil {
		return datingIntentionObj, err
	}

	return datingIntentionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DatingIntention) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no dating_intentions provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(datingIntentionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	datingIntentionInsertCacheMut.RLock()
	cache, cached := datingIntentionInsertCache[key]
	datingIntentionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			datingIntentionAllColumns,
			datingIntentionColumnsWithDefault,
			datingIntentionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(datingIntentionType, datingIntentionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(datingIntentionType, datingIntentionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"dating_intentions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"dating_intentions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "entity: unable to insert into dating_intentions")
	}

	if !cached {
		datingIntentionInsertCacheMut.Lock()
		datingIntentionInsertCache[key] = cache
		datingIntentionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the DatingIntention.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DatingIntention) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	datingIntentionUpdateCacheMut.RLock()
	cache, cached := datingIntentionUpdateCache[key]
	datingIntentionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			datingIntentionAllColumns,
			datingIntentionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("entity: unable to update dating_intentions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"dating_intentions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, datingIntentionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(datingIntentionType, datingIntentionMapping, append(wl, datingIntentionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update dating_intentions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by update for dating_intentions")
	}

	if !cached {
		datingIntentionUpdateCacheMut.Lock()
		datingIntentionUpdateCache[key] = cache
		datingIntentionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q datingIntentionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all for dating_intentions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected for dating_intentions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DatingIntentionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("entity: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), datingIntentionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"dating_intentions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, datingIntentionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all in datingIntention slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected all in update all datingIntention")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DatingIntention) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("entity: no dating_intentions provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(datingIntentionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	datingIntentionUpsertCacheMut.RLock()
	cache, cached := datingIntentionUpsertCache[key]
	datingIntentionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			datingIntentionAllColumns,
			datingIntentionColumnsWithDefault,
			datingIntentionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			datingIntentionAllColumns,
			datingIntentionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("entity: unable to upsert dating_intentions, could not build update column list")
		}

		ret := strmangle.SetComplement(datingIntentionAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(datingIntentionPrimaryKeyColumns) == 0 {
				return errors.New("entity: unable to upsert dating_intentions, could not build conflict column list")
			}

			conflict = make([]string, len(datingIntentionPrimaryKeyColumns))
			copy(conflict, datingIntentionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"dating_intentions\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(datingIntentionType, datingIntentionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(datingIntentionType, datingIntentionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "entity: unable to upsert dating_intentions")
	}

	if !cached {
		datingIntentionUpsertCacheMut.Lock()
		datingIntentionUpsertCache[key] = cache
		datingIntentionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single DatingIntention record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DatingIntention) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("entity: no DatingIntention provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), datingIntentionPrimaryKeyMapping)
	sql := "DELETE FROM \"dating_intentions\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete from dating_intentions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by delete for dating_intentions")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q datingIntentionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("entity: no datingIntentionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from dating_intentions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for dating_intentions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DatingIntentionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(datingIntentionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), datingIntentionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"dating_intentions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, datingIntentionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from datingIntention slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for dating_intentions")
	}

	if len(datingIntentionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DatingIntention) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDatingIntention(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DatingIntentionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DatingIntentionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), datingIntentionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"dating_intentions\".* FROM \"dating_intentions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, datingIntentionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "entity: unable to reload all in DatingIntentionSlice")
	}

	*o = slice

	return nil
}

// DatingIntentionExists checks if the DatingIntention row exists.
func DatingIntentionExists(ctx context.Context, exec boil.ContextExecutor, iD int16) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"dating_intentions\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "entity: unable to check if dating_intentions exists")
	}

	return exists, nil
}

// Exists checks if the DatingIntention row exists.
func (o *DatingIntention) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DatingIntentionExists(ctx, exec, o.ID)
}
