// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// EducationLevel is an object representing the database table.
type EducationLevel struct {
	ID    int16  `boil:"id" json:"id" toml:"id" yaml:"id"`
	Label string `boil:"label" json:"label" toml:"label" yaml:"label"`

	R *educationLevelR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L educationLevelL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EducationLevelColumns = struct {
	ID    string
	Label string
}{
	ID:    "id",
	Label: "label",
}

var EducationLevelTableColumns = struct {
	ID    string
	Label string
}{
	ID:    "education_levels.id",
	Label: "education_levels.label",
}

// Generated where

var EducationLevelWhere = struct {
	ID    whereHelperint16
	Label whereHelperstring
}{
	ID:    whereHelperint16{field: "\"education_levels\".\"id\""},
	Label: whereHelperstring{field: "\"education_levels\".\"label\""},
}

// EducationLevelRels is where relationship names are stored.
var EducationLevelRels = struct {
	UserProfiles string
}{
	UserProfiles: "UserProfiles",
}

// educationLevelR is where relationships are stored.
type educationLevelR struct {
	UserProfiles UserProfileSlice `boil:"UserProfiles" json:"UserProfiles" toml:"UserProfiles" yaml:"UserProfiles"`
}

// NewStruct creates a new relationship struct
func (*educationLevelR) NewStruct() *educationLevelR {
	return &educationLevelR{}
}

func (o *EducationLevel) GetUserProfiles() UserProfileSlice {
	if o == nil {
		return nil
	}

	return o.R.GetUserProfiles()
}

func (r *educationLevelR) GetUserProfiles() UserProfileSlice {
	if r == nil {
		return nil
	}

	return r.UserProfiles
}

// educationLevelL is where Load methods for each relationship are stored.
type educationLevelL struct{}

var (
	educationLevelAllColumns            = []string{"id", "label"}
	educationLevelColumnsWithoutDefault = []string{"label"}
	educationLevelColumnsWithDefault    = []string{"id"}
	educationLevelPrimaryKeyColumns     = []string{"id"}
	educationLevelGeneratedColumns      = []string{}
)

type (
	// EducationLevelSlice is an alias for a slice of pointers to EducationLevel.
	// This should almost always be used instead of []EducationLevel.
	EducationLevelSlice []*EducationLevel
	// EducationLevelHook is the signature for custom EducationLevel hook methods
	EducationLevelHook func(context.Context, boil.ContextExecutor, *EducationLevel) error

	educationLevelQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	educationLevelType                 = reflect.TypeOf(&EducationLevel{})
	educationLevelMapping              = queries.MakeStructMapping(educationLevelType)
	educationLevelPrimaryKeyMapping, _ = queries.BindMapping(educationLevelType, educationLevelMapping, educationLevelPrimaryKeyColumns)
	educationLevelInsertCacheMut       sync.RWMutex
	educationLevelInsertCache          = make(map[string]insertCache)
	educationLevelUpdateCacheMut       sync.RWMutex
	educationLevelUpdateCache          = make(map[string]updateCache)
	educationLevelUpsertCacheMut       sync.RWMutex
	educationLevelUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var educationLevelAfterSelectMu sync.Mutex
var educationLevelAfterSelectHooks []EducationLevelHook

var educationLevelBeforeInsertMu sync.Mutex
var educationLevelBeforeInsertHooks []EducationLevelHook
var educationLevelAfterInsertMu sync.Mutex
var educationLevelAfterInsertHooks []EducationLevelHook

var educationLevelBeforeUpdateMu sync.Mutex
var educationLevelBeforeUpdateHooks []EducationLevelHook
var educationLevelAfterUpdateMu sync.Mutex
var educationLevelAfterUpdateHooks []EducationLevelHook

var educationLevelBeforeDeleteMu sync.Mutex
var educationLevelBeforeDeleteHooks []EducationLevelHook
var educationLevelAfterDeleteMu sync.Mutex
var educationLevelAfterDeleteHooks []EducationLevelHook

var educationLevelBeforeUpsertMu sync.Mutex
var educationLevelBeforeUpsertHooks []EducationLevelHook
var educationLevelAfterUpsertMu sync.Mutex
var educationLevelAfterUpsertHooks []EducationLevelHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EducationLevel) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range educationLevelAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EducationLevel) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range educationLevelBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EducationLevel) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range educationLevelAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EducationLevel) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range educationLevelBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EducationLevel) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range educationLevelAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EducationLevel) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range educationLevelBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EducationLevel) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range educationLevelAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EducationLevel) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range educationLevelBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EducationLevel) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range educationLevelAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEducationLevelHook registers your hook function for all future operations.
func AddEducationLevelHook(hookPoint boil.HookPoint, educationLevelHook EducationLevelHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		educationLevelAfterSelectMu.Lock()
		educationLevelAfterSelectHooks = append(educationLevelAfterSelectHooks, educationLevelHook)
		educationLevelAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		educationLevelBeforeInsertMu.Lock()
		educationLevelBeforeInsertHooks = append(educationLevelBeforeInsertHooks, educationLevelHook)
		educationLevelBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		educationLevelAfterInsertMu.Lock()
		educationLevelAfterInsertHooks = append(educationLevelAfterInsertHooks, educationLevelHook)
		educationLevelAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		educationLevelBeforeUpdateMu.Lock()
		educationLevelBeforeUpdateHooks = append(educationLevelBeforeUpdateHooks, educationLevelHook)
		educationLevelBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		educationLevelAfterUpdateMu.Lock()
		educationLevelAfterUpdateHooks = append(educationLevelAfterUpdateHooks, educationLevelHook)
		educationLevelAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		educationLevelBeforeDeleteMu.Lock()
		educationLevelBeforeDeleteHooks = append(educationLevelBeforeDeleteHooks, educationLevelHook)
		educationLevelBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		educationLevelAfterDeleteMu.Lock()
		educationLevelAfterDeleteHooks = append(educationLevelAfterDeleteHooks, educationLevelHook)
		educationLevelAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		educationLevelBeforeUpsertMu.Lock()
		educationLevelBeforeUpsertHooks = append(educationLevelBeforeUpsertHooks, educationLevelHook)
		educationLevelBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		educationLevelAfterUpsertMu.Lock()
		educationLevelAfterUpsertHooks = append(educationLevelAfterUpsertHooks, educationLevelHook)
		educationLevelAfterUpsertMu.Unlock()
	}
}

// One returns a single educationLevel record from the query.
func (q educationLevelQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EducationLevel, error) {
	o := &EducationLevel{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: failed to execute a one query for education_levels")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EducationLevel records from the query.
func (q educationLevelQuery) All(ctx context.Context, exec boil.ContextExecutor) (EducationLevelSlice, error) {
	var o []*EducationLevel

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "entity: failed to assign all query results to EducationLevel slice")
	}

	if len(educationLevelAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EducationLevel records in the query.
func (q educationLevelQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to count education_levels rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q educationLevelQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "entity: failed to check if education_levels exists")
	}

	return count > 0, nil
}

// UserProfiles retrieves all the user_profile's UserProfiles with an executor.
func (o *EducationLevel) UserProfiles(mods ...qm.QueryMod) userProfileQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"user_profiles\".\"education_level_id\"=?", o.ID),
	)

	return UserProfiles(queryMods...)
}

// LoadUserProfiles allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (educationLevelL) LoadUserProfiles(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEducationLevel interface{}, mods queries.Applicator) error {
	var slice []*EducationLevel
	var object *EducationLevel

	if singular {
		var ok bool
		object, ok = maybeEducationLevel.(*EducationLevel)
		if !ok {
			object = new(EducationLevel)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeEducationLevel)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeEducationLevel))
			}
		}
	} else {
		s, ok := maybeEducationLevel.(*[]*EducationLevel)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeEducationLevel)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeEducationLevel))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &educationLevelR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &educationLevelR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`user_profiles`),
		qm.WhereIn(`user_profiles.education_level_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load user_profiles")
	}

	var resultSlice []*UserProfile
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice user_profiles")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on user_profiles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user_profiles")
	}

	if len(userProfileAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.UserProfiles = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &userProfileR{}
			}
			foreign.R.EducationLevel = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.EducationLevelID) {
				local.R.UserProfiles = append(local.R.UserProfiles, foreign)
				if foreign.R == nil {
					foreign.R = &userProfileR{}
				}
				foreign.R.EducationLevel = local
				break
			}
		}
	}

	return nil
}

// AddUserProfiles adds the given related objects to the existing relationships
// of the education_level, optionally inserting them as new records.
// Appends related to o.R.UserProfiles.
// Sets related.R.EducationLevel appropriately.
func (o *EducationLevel) AddUserProfiles(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*UserProfile) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.EducationLevelID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"user_profiles\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"education_level_id"}),
				strmangle.WhereClause("\"", "\"", 2, userProfilePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.UserID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.EducationLevelID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &educationLevelR{
			UserProfiles: related,
		}
	} else {
		o.R.UserProfiles = append(o.R.UserProfiles, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &userProfileR{
				EducationLevel: o,
			}
		} else {
			rel.R.EducationLevel = o
		}
	}
	return nil
}

// SetUserProfiles removes all previously related items of the
// education_level replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.EducationLevel's UserProfiles accordingly.
// Replaces o.R.UserProfiles with related.
// Sets related.R.EducationLevel's UserProfiles accordingly.
func (o *EducationLevel) SetUserProfiles(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*UserProfile) error {
	query := "update \"user_profiles\" set \"education_level_id\" = null where \"education_level_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.UserProfiles {
			queries.SetScanner(&rel.EducationLevelID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.EducationLevel = nil
		}
		o.R.UserProfiles = nil
	}

	return o.AddUserProfiles(ctx, exec, insert, related...)
}

// RemoveUserProfiles relationships from objects passed in.
// Removes related items from R.UserProfiles (uses pointer comparison, removal does not keep order)
// Sets related.R.EducationLevel.
func (o *EducationLevel) RemoveUserProfiles(ctx context.Context, exec boil.ContextExecutor, related ...*UserProfile) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.EducationLevelID, nil)
		if rel.R != nil {
			rel.R.EducationLevel = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("education_level_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.UserProfiles {
			if rel != ri {
				continue
			}

			ln := len(o.R.UserProfiles)
			if ln > 1 && i < ln-1 {
				o.R.UserProfiles[i] = o.R.UserProfiles[ln-1]
			}
			o.R.UserProfiles = o.R.UserProfiles[:ln-1]
			break
		}
	}

	return nil
}

// EducationLevels retrieves all the records using an executor.
func EducationLevels(mods ...qm.QueryMod) educationLevelQuery {
	mods = append(mods, qm.From("\"education_levels\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"education_levels\".*"})
	}

	return educationLevelQuery{q}
}

// FindEducationLevel retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEducationLevel(ctx context.Context, exec boil.ContextExecutor, iD int16, selectCols ...string) (*EducationLevel, error) {
	educationLevelObj := &EducationLevel{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"education_levels\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, educationLevelObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: unable to select from education_levels")
	}

	if err = educationLevelObj.doAfterSelectHooks(ctx, exec); err != nil {
		return educationLevelObj, err
	}

	return educationLevelObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EducationLevel) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no education_levels provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(educationLevelColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	educationLevelInsertCacheMut.RLock()
	cache, cached := educationLevelInsertCache[key]
	educationLevelInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			educationLevelAllColumns,
			educationLevelColumnsWithDefault,
			educationLevelColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(educationLevelType, educationLevelMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(educationLevelType, educationLevelMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"education_levels\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"education_levels\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "entity: unable to insert into education_levels")
	}

	if !cached {
		educationLevelInsertCacheMut.Lock()
		educationLevelInsertCache[key] = cache
		educationLevelInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the EducationLevel.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EducationLevel) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	educationLevelUpdateCacheMut.RLock()
	cache, cached := educationLevelUpdateCache[key]
	educationLevelUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			educationLevelAllColumns,
			educationLevelPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("entity: unable to update education_levels, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"education_levels\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, educationLevelPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(educationLevelType, educationLevelMapping, append(wl, educationLevelPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update education_levels row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by update for education_levels")
	}

	if !cached {
		educationLevelUpdateCacheMut.Lock()
		educationLevelUpdateCache[key] = cache
		educationLevelUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q educationLevelQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all for education_levels")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected for education_levels")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EducationLevelSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("entity: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), educationLevelPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"education_levels\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, educationLevelPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all in educationLevel slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected all in update all educationLevel")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EducationLevel) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("entity: no education_levels provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(educationLevelColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	educationLevelUpsertCacheMut.RLock()
	cache, cached := educationLevelUpsertCache[key]
	educationLevelUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			educationLevelAllColumns,
			educationLevelColumnsWithDefault,
			educationLevelColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			educationLevelAllColumns,
			educationLevelPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("entity: unable to upsert education_levels, could not build update column list")
		}

		ret := strmangle.SetComplement(educationLevelAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(educationLevelPrimaryKeyColumns) == 0 {
				return errors.New("entity: unable to upsert education_levels, could not build conflict column list")
			}

			conflict = make([]string, len(educationLevelPrimaryKeyColumns))
			copy(conflict, educationLevelPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"education_levels\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(educationLevelType, educationLevelMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(educationLevelType, educationLevelMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "entity: unable to upsert education_levels")
	}

	if !cached {
		educationLevelUpsertCacheMut.Lock()
		educationLevelUpsertCache[key] = cache
		educationLevelUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single EducationLevel record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EducationLevel) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("entity: no EducationLevel provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), educationLevelPrimaryKeyMapping)
	sql := "DELETE FROM \"education_levels\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete from education_levels")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by delete for education_levels")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q educationLevelQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("entity: no educationLevelQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from education_levels")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for education_levels")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EducationLevelSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(educationLevelBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), educationLevelPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"education_levels\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, educationLevelPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from educationLevel slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for education_levels")
	}

	if len(educationLevelAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EducationLevel) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEducationLevel(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EducationLevelSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EducationLevelSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), educationLevelPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"education_levels\".* FROM \"education_levels\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, educationLevelPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "entity: unable to reload all in EducationLevelSlice")
	}

	*o = slice

	return nil
}

// EducationLevelExists checks if the EducationLevel row exists.
func EducationLevelExists(ctx context.Context, exec boil.ContextExecutor, iD int16) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"education_levels\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "entity: unable to check if education_levels exists")
	}

	return exists, nil
}

// Exists checks if the EducationLevel row exists.
func (o *EducationLevel) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EducationLevelExists(ctx, exec, o.ID)
}
