// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPhotos(t *testing.T) {
	t.Parallel()

	query := Photos()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPhotosDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Photos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPhotosQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Photos().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Photos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPhotosSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PhotoSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Photos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPhotosExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PhotoExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Photo exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PhotoExists to return true, but got false.")
	}
}

func testPhotosFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	photoFound, err := FindPhoto(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if photoFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPhotosBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Photos().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPhotosOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Photos().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPhotosAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	photoOne := &Photo{}
	photoTwo := &Photo{}
	if err = randomize.Struct(seed, photoOne, photoDBTypes, false, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}
	if err = randomize.Struct(seed, photoTwo, photoDBTypes, false, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = photoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = photoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Photos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPhotosCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	photoOne := &Photo{}
	photoTwo := &Photo{}
	if err = randomize.Struct(seed, photoOne, photoDBTypes, false, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}
	if err = randomize.Struct(seed, photoTwo, photoDBTypes, false, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = photoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = photoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Photos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func photoBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Photo) error {
	*o = Photo{}
	return nil
}

func photoAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Photo) error {
	*o = Photo{}
	return nil
}

func photoAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Photo) error {
	*o = Photo{}
	return nil
}

func photoBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Photo) error {
	*o = Photo{}
	return nil
}

func photoAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Photo) error {
	*o = Photo{}
	return nil
}

func photoBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Photo) error {
	*o = Photo{}
	return nil
}

func photoAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Photo) error {
	*o = Photo{}
	return nil
}

func photoBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Photo) error {
	*o = Photo{}
	return nil
}

func photoAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Photo) error {
	*o = Photo{}
	return nil
}

func testPhotosHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Photo{}
	o := &Photo{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, photoDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Photo object: %s", err)
	}

	AddPhotoHook(boil.BeforeInsertHook, photoBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	photoBeforeInsertHooks = []PhotoHook{}

	AddPhotoHook(boil.AfterInsertHook, photoAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	photoAfterInsertHooks = []PhotoHook{}

	AddPhotoHook(boil.AfterSelectHook, photoAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	photoAfterSelectHooks = []PhotoHook{}

	AddPhotoHook(boil.BeforeUpdateHook, photoBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	photoBeforeUpdateHooks = []PhotoHook{}

	AddPhotoHook(boil.AfterUpdateHook, photoAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	photoAfterUpdateHooks = []PhotoHook{}

	AddPhotoHook(boil.BeforeDeleteHook, photoBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	photoBeforeDeleteHooks = []PhotoHook{}

	AddPhotoHook(boil.AfterDeleteHook, photoAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	photoAfterDeleteHooks = []PhotoHook{}

	AddPhotoHook(boil.BeforeUpsertHook, photoBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	photoBeforeUpsertHooks = []PhotoHook{}

	AddPhotoHook(boil.AfterUpsertHook, photoAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	photoAfterUpsertHooks = []PhotoHook{}
}

func testPhotosInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Photos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPhotosInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(photoPrimaryKeyColumns, photoColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Photos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPhotoToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Photo
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.UserID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := PhotoSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*Photo)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testPhotoToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Photo
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, photoDBTypes, false, strmangle.SetComplement(photoPrimaryKeyColumns, photoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Photos[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.UserID, x.ID) {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.UserID, x.ID) {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testPhotoToOneRemoveOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Photo
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, photoDBTypes, false, strmangle.SetComplement(photoPrimaryKeyColumns, photoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetUser(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveUser(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.User().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.User != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.UserID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.Photos) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testPhotosReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPhotosReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PhotoSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPhotosSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Photos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	photoDBTypes = map[string]string{`ID`: `bigint`, `UserID`: `uuid`, `URL`: `text`, `Position`: `smallint`, `IsPrimary`: `boolean`, `IsHiddenUntilReveal`: `boolean`, `CreatedAt`: `timestamp with time zone`}
	_            = bytes.MinRead
)

func testPhotosUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(photoPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(photoAllColumns) == len(photoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Photos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, photoDBTypes, true, photoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPhotosSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(photoAllColumns) == len(photoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Photo{}
	if err = randomize.Struct(seed, o, photoDBTypes, true, photoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Photos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, photoDBTypes, true, photoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(photoAllColumns, photoPrimaryKeyColumns) {
		fields = photoAllColumns
	} else {
		fields = strmangle.SetComplement(
			photoAllColumns,
			photoPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PhotoSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPhotosUpsert(t *testing.T) {
	t.Parallel()

	if len(photoAllColumns) == len(photoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Photo{}
	if err = randomize.Struct(seed, &o, photoDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Photo: %s", err)
	}

	count, err := Photos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, photoDBTypes, false, photoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Photo struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Photo: %s", err)
	}

	count, err = Photos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
