// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("ConversationParticipants", testConversationParticipantsUpsert)

	t.Run("Conversations", testConversationsUpsert)

	t.Run("DatingIntentions", testDatingIntentionsUpsert)

	t.Run("DeviceTokens", testDeviceTokensUpsert)

	t.Run("EducationLevels", testEducationLevelsUpsert)

	t.Run("Ethnicities", testEthnicitiesUpsert)

	t.Run("FamilyPlans", testFamilyPlansUpsert)

	t.Run("FamilyStatuses", testFamilyStatusesUpsert)

	t.Run("Genders", testGendersUpsert)

	t.Run("GooseDBVersions", testGooseDBVersionsUpsert)

	t.Run("Habits", testHabitsUpsert)

	t.Run("ImportanceWeights", testImportanceWeightsUpsert)

	t.Run("Interests", testInterestsUpsert)

	t.Run("Languages", testLanguagesUpsert)

	t.Run("Matches", testMatchesUpsert)

	t.Run("MessageReceipts", testMessageReceiptsUpsert)

	t.Run("Messages", testMessagesUpsert)

	t.Run("Photos", testPhotosUpsert)

	t.Run("PoliticalBeliefs", testPoliticalBeliefsUpsert)

	t.Run("PromptTypes", testPromptTypesUpsert)

	t.Run("QuestionAnswers", testQuestionAnswersUpsert)

	t.Run("QuestionCategories", testQuestionCategoriesUpsert)

	t.Run("Questions", testQuestionsUpsert)

	t.Run("RefreshTokens", testRefreshTokensUpsert)

	t.Run("Religions", testReligionsUpsert)

	t.Run("RevealDecisions", testRevealDecisionsUpsert)

	t.Run("RevealRequests", testRevealRequestsUpsert)

	t.Run("ScoringBonuses", testScoringBonusesUpsert)

	t.Run("ScoringCalls", testScoringCallsUpsert)

	t.Run("ScoringPenalties", testScoringPenaltiesUpsert)

	t.Run("ScoringSettings", testScoringSettingsUpsert)

	t.Run("ScoringTexts", testScoringTextsUpsert)

	t.Run("ScoringVoices", testScoringVoicesUpsert)

	t.Run("SpatialRefSys", testSpatialRefSysUpsert)

	t.Run("Swipes", testSwipesUpsert)

	t.Run("UserAnswers", testUserAnswersUpsert)

	t.Run("UserPreferences", testUserPreferencesUpsert)

	t.Run("UserProfileVisibilities", testUserProfileVisibilitiesUpsert)

	t.Run("UserProfiles", testUserProfilesUpsert)

	t.Run("UserThemes", testUserThemesUpsert)

	t.Run("UserVerificationStatuses", testUserVerificationStatusesUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("VerificationAttempts", testVerificationAttemptsUpsert)

	t.Run("VerificationCodes", testVerificationCodesUpsert)

	t.Run("VoicePrompts", testVoicePromptsUpsert)

	t.Run("VoiceWorthHearingWeeklies", testVoiceWorthHearingWeekliesUpsert)
}
