// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testQuestionCategories(t *testing.T) {
	t.Parallel()

	query := QuestionCategories()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testQuestionCategoriesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := QuestionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testQuestionCategoriesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := QuestionCategories().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := QuestionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testQuestionCategoriesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := QuestionCategorySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := QuestionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testQuestionCategoriesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := QuestionCategoryExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if QuestionCategory exists: %s", err)
	}
	if !e {
		t.Errorf("Expected QuestionCategoryExists to return true, but got false.")
	}
}

func testQuestionCategoriesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	questionCategoryFound, err := FindQuestionCategory(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if questionCategoryFound == nil {
		t.Error("want a record, got nil")
	}
}

func testQuestionCategoriesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = QuestionCategories().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testQuestionCategoriesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := QuestionCategories().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testQuestionCategoriesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	questionCategoryOne := &QuestionCategory{}
	questionCategoryTwo := &QuestionCategory{}
	if err = randomize.Struct(seed, questionCategoryOne, questionCategoryDBTypes, false, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}
	if err = randomize.Struct(seed, questionCategoryTwo, questionCategoryDBTypes, false, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = questionCategoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = questionCategoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := QuestionCategories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testQuestionCategoriesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	questionCategoryOne := &QuestionCategory{}
	questionCategoryTwo := &QuestionCategory{}
	if err = randomize.Struct(seed, questionCategoryOne, questionCategoryDBTypes, false, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}
	if err = randomize.Struct(seed, questionCategoryTwo, questionCategoryDBTypes, false, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = questionCategoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = questionCategoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := QuestionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func questionCategoryBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *QuestionCategory) error {
	*o = QuestionCategory{}
	return nil
}

func questionCategoryAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *QuestionCategory) error {
	*o = QuestionCategory{}
	return nil
}

func questionCategoryAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *QuestionCategory) error {
	*o = QuestionCategory{}
	return nil
}

func questionCategoryBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *QuestionCategory) error {
	*o = QuestionCategory{}
	return nil
}

func questionCategoryAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *QuestionCategory) error {
	*o = QuestionCategory{}
	return nil
}

func questionCategoryBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *QuestionCategory) error {
	*o = QuestionCategory{}
	return nil
}

func questionCategoryAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *QuestionCategory) error {
	*o = QuestionCategory{}
	return nil
}

func questionCategoryBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *QuestionCategory) error {
	*o = QuestionCategory{}
	return nil
}

func questionCategoryAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *QuestionCategory) error {
	*o = QuestionCategory{}
	return nil
}

func testQuestionCategoriesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &QuestionCategory{}
	o := &QuestionCategory{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize QuestionCategory object: %s", err)
	}

	AddQuestionCategoryHook(boil.BeforeInsertHook, questionCategoryBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	questionCategoryBeforeInsertHooks = []QuestionCategoryHook{}

	AddQuestionCategoryHook(boil.AfterInsertHook, questionCategoryAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	questionCategoryAfterInsertHooks = []QuestionCategoryHook{}

	AddQuestionCategoryHook(boil.AfterSelectHook, questionCategoryAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	questionCategoryAfterSelectHooks = []QuestionCategoryHook{}

	AddQuestionCategoryHook(boil.BeforeUpdateHook, questionCategoryBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	questionCategoryBeforeUpdateHooks = []QuestionCategoryHook{}

	AddQuestionCategoryHook(boil.AfterUpdateHook, questionCategoryAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	questionCategoryAfterUpdateHooks = []QuestionCategoryHook{}

	AddQuestionCategoryHook(boil.BeforeDeleteHook, questionCategoryBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	questionCategoryBeforeDeleteHooks = []QuestionCategoryHook{}

	AddQuestionCategoryHook(boil.AfterDeleteHook, questionCategoryAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	questionCategoryAfterDeleteHooks = []QuestionCategoryHook{}

	AddQuestionCategoryHook(boil.BeforeUpsertHook, questionCategoryBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	questionCategoryBeforeUpsertHooks = []QuestionCategoryHook{}

	AddQuestionCategoryHook(boil.AfterUpsertHook, questionCategoryAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	questionCategoryAfterUpsertHooks = []QuestionCategoryHook{}
}

func testQuestionCategoriesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := QuestionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testQuestionCategoriesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(questionCategoryPrimaryKeyColumns, questionCategoryColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := QuestionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testQuestionCategoryToManyCategoryQuestions(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a QuestionCategory
	var b, c Question

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, questionDBTypes, false, questionColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, questionDBTypes, false, questionColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.CategoryID = a.ID
	c.CategoryID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.CategoryQuestions().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.CategoryID == b.CategoryID {
			bFound = true
		}
		if v.CategoryID == c.CategoryID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := QuestionCategorySlice{&a}
	if err = a.L.LoadCategoryQuestions(ctx, tx, false, (*[]*QuestionCategory)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.CategoryQuestions); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.CategoryQuestions = nil
	if err = a.L.LoadCategoryQuestions(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.CategoryQuestions); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testQuestionCategoryToManyAddOpCategoryQuestions(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a QuestionCategory
	var b, c, d, e Question

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, questionCategoryDBTypes, false, strmangle.SetComplement(questionCategoryPrimaryKeyColumns, questionCategoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Question{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, questionDBTypes, false, strmangle.SetComplement(questionPrimaryKeyColumns, questionColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Question{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddCategoryQuestions(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.CategoryID {
			t.Error("foreign key was wrong value", a.ID, first.CategoryID)
		}
		if a.ID != second.CategoryID {
			t.Error("foreign key was wrong value", a.ID, second.CategoryID)
		}

		if first.R.Category != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Category != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.CategoryQuestions[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.CategoryQuestions[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.CategoryQuestions().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testQuestionCategoriesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testQuestionCategoriesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := QuestionCategorySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testQuestionCategoriesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := QuestionCategories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	questionCategoryDBTypes = map[string]string{`ID`: `bigint`, `Key`: `text`, `Name`: `text`, `CreatedAt`: `timestamp with time zone`}
	_                       = bytes.MinRead
)

func testQuestionCategoriesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(questionCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(questionCategoryAllColumns) == len(questionCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := QuestionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testQuestionCategoriesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(questionCategoryAllColumns) == len(questionCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &QuestionCategory{}
	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := QuestionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, questionCategoryDBTypes, true, questionCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(questionCategoryAllColumns, questionCategoryPrimaryKeyColumns) {
		fields = questionCategoryAllColumns
	} else {
		fields = strmangle.SetComplement(
			questionCategoryAllColumns,
			questionCategoryPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := QuestionCategorySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testQuestionCategoriesUpsert(t *testing.T) {
	t.Parallel()

	if len(questionCategoryAllColumns) == len(questionCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := QuestionCategory{}
	if err = randomize.Struct(seed, &o, questionCategoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert QuestionCategory: %s", err)
	}

	count, err := QuestionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, questionCategoryDBTypes, false, questionCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize QuestionCategory struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert QuestionCategory: %s", err)
	}

	count, err = QuestionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
