// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ScoringCall is an object representing the database table.
type ScoringCall struct {
	ID                 int64         `boil:"id" json:"id" toml:"id" yaml:"id"`
	PerMinute          types.Decimal `boil:"per_minute" json:"per_minute" toml:"per_minute" yaml:"per_minute"`
	MaxPerCall         types.Decimal `boil:"max_per_call" json:"max_per_call" toml:"max_per_call" yaml:"max_per_call"`
	MinDurationSeconds int           `boil:"min_duration_seconds" json:"min_duration_seconds" toml:"min_duration_seconds" yaml:"min_duration_seconds"`
	CreatedAt          time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *scoringCallR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L scoringCallL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ScoringCallColumns = struct {
	ID                 string
	PerMinute          string
	MaxPerCall         string
	MinDurationSeconds string
	CreatedAt          string
}{
	ID:                 "id",
	PerMinute:          "per_minute",
	MaxPerCall:         "max_per_call",
	MinDurationSeconds: "min_duration_seconds",
	CreatedAt:          "created_at",
}

var ScoringCallTableColumns = struct {
	ID                 string
	PerMinute          string
	MaxPerCall         string
	MinDurationSeconds string
	CreatedAt          string
}{
	ID:                 "scoring_call.id",
	PerMinute:          "scoring_call.per_minute",
	MaxPerCall:         "scoring_call.max_per_call",
	MinDurationSeconds: "scoring_call.min_duration_seconds",
	CreatedAt:          "scoring_call.created_at",
}

// Generated where

var ScoringCallWhere = struct {
	ID                 whereHelperint64
	PerMinute          whereHelpertypes_Decimal
	MaxPerCall         whereHelpertypes_Decimal
	MinDurationSeconds whereHelperint
	CreatedAt          whereHelpertime_Time
}{
	ID:                 whereHelperint64{field: "\"scoring_call\".\"id\""},
	PerMinute:          whereHelpertypes_Decimal{field: "\"scoring_call\".\"per_minute\""},
	MaxPerCall:         whereHelpertypes_Decimal{field: "\"scoring_call\".\"max_per_call\""},
	MinDurationSeconds: whereHelperint{field: "\"scoring_call\".\"min_duration_seconds\""},
	CreatedAt:          whereHelpertime_Time{field: "\"scoring_call\".\"created_at\""},
}

// ScoringCallRels is where relationship names are stored.
var ScoringCallRels = struct {
}{}

// scoringCallR is where relationships are stored.
type scoringCallR struct {
}

// NewStruct creates a new relationship struct
func (*scoringCallR) NewStruct() *scoringCallR {
	return &scoringCallR{}
}

// scoringCallL is where Load methods for each relationship are stored.
type scoringCallL struct{}

var (
	scoringCallAllColumns            = []string{"id", "per_minute", "max_per_call", "min_duration_seconds", "created_at"}
	scoringCallColumnsWithoutDefault = []string{"per_minute", "max_per_call", "min_duration_seconds"}
	scoringCallColumnsWithDefault    = []string{"id", "created_at"}
	scoringCallPrimaryKeyColumns     = []string{"id"}
	scoringCallGeneratedColumns      = []string{}
)

type (
	// ScoringCallSlice is an alias for a slice of pointers to ScoringCall.
	// This should almost always be used instead of []ScoringCall.
	ScoringCallSlice []*ScoringCall
	// ScoringCallHook is the signature for custom ScoringCall hook methods
	ScoringCallHook func(context.Context, boil.ContextExecutor, *ScoringCall) error

	scoringCallQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	scoringCallType                 = reflect.TypeOf(&ScoringCall{})
	scoringCallMapping              = queries.MakeStructMapping(scoringCallType)
	scoringCallPrimaryKeyMapping, _ = queries.BindMapping(scoringCallType, scoringCallMapping, scoringCallPrimaryKeyColumns)
	scoringCallInsertCacheMut       sync.RWMutex
	scoringCallInsertCache          = make(map[string]insertCache)
	scoringCallUpdateCacheMut       sync.RWMutex
	scoringCallUpdateCache          = make(map[string]updateCache)
	scoringCallUpsertCacheMut       sync.RWMutex
	scoringCallUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var scoringCallAfterSelectMu sync.Mutex
var scoringCallAfterSelectHooks []ScoringCallHook

var scoringCallBeforeInsertMu sync.Mutex
var scoringCallBeforeInsertHooks []ScoringCallHook
var scoringCallAfterInsertMu sync.Mutex
var scoringCallAfterInsertHooks []ScoringCallHook

var scoringCallBeforeUpdateMu sync.Mutex
var scoringCallBeforeUpdateHooks []ScoringCallHook
var scoringCallAfterUpdateMu sync.Mutex
var scoringCallAfterUpdateHooks []ScoringCallHook

var scoringCallBeforeDeleteMu sync.Mutex
var scoringCallBeforeDeleteHooks []ScoringCallHook
var scoringCallAfterDeleteMu sync.Mutex
var scoringCallAfterDeleteHooks []ScoringCallHook

var scoringCallBeforeUpsertMu sync.Mutex
var scoringCallBeforeUpsertHooks []ScoringCallHook
var scoringCallAfterUpsertMu sync.Mutex
var scoringCallAfterUpsertHooks []ScoringCallHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ScoringCall) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scoringCallAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ScoringCall) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scoringCallBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ScoringCall) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scoringCallAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ScoringCall) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scoringCallBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ScoringCall) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scoringCallAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ScoringCall) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scoringCallBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ScoringCall) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scoringCallAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ScoringCall) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scoringCallBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ScoringCall) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scoringCallAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddScoringCallHook registers your hook function for all future operations.
func AddScoringCallHook(hookPoint boil.HookPoint, scoringCallHook ScoringCallHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		scoringCallAfterSelectMu.Lock()
		scoringCallAfterSelectHooks = append(scoringCallAfterSelectHooks, scoringCallHook)
		scoringCallAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		scoringCallBeforeInsertMu.Lock()
		scoringCallBeforeInsertHooks = append(scoringCallBeforeInsertHooks, scoringCallHook)
		scoringCallBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		scoringCallAfterInsertMu.Lock()
		scoringCallAfterInsertHooks = append(scoringCallAfterInsertHooks, scoringCallHook)
		scoringCallAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		scoringCallBeforeUpdateMu.Lock()
		scoringCallBeforeUpdateHooks = append(scoringCallBeforeUpdateHooks, scoringCallHook)
		scoringCallBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		scoringCallAfterUpdateMu.Lock()
		scoringCallAfterUpdateHooks = append(scoringCallAfterUpdateHooks, scoringCallHook)
		scoringCallAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		scoringCallBeforeDeleteMu.Lock()
		scoringCallBeforeDeleteHooks = append(scoringCallBeforeDeleteHooks, scoringCallHook)
		scoringCallBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		scoringCallAfterDeleteMu.Lock()
		scoringCallAfterDeleteHooks = append(scoringCallAfterDeleteHooks, scoringCallHook)
		scoringCallAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		scoringCallBeforeUpsertMu.Lock()
		scoringCallBeforeUpsertHooks = append(scoringCallBeforeUpsertHooks, scoringCallHook)
		scoringCallBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		scoringCallAfterUpsertMu.Lock()
		scoringCallAfterUpsertHooks = append(scoringCallAfterUpsertHooks, scoringCallHook)
		scoringCallAfterUpsertMu.Unlock()
	}
}

// One returns a single scoringCall record from the query.
func (q scoringCallQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ScoringCall, error) {
	o := &ScoringCall{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: failed to execute a one query for scoring_call")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ScoringCall records from the query.
func (q scoringCallQuery) All(ctx context.Context, exec boil.ContextExecutor) (ScoringCallSlice, error) {
	var o []*ScoringCall

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "entity: failed to assign all query results to ScoringCall slice")
	}

	if len(scoringCallAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ScoringCall records in the query.
func (q scoringCallQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to count scoring_call rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q scoringCallQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "entity: failed to check if scoring_call exists")
	}

	return count > 0, nil
}

// ScoringCalls retrieves all the records using an executor.
func ScoringCalls(mods ...qm.QueryMod) scoringCallQuery {
	mods = append(mods, qm.From("\"scoring_call\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"scoring_call\".*"})
	}

	return scoringCallQuery{q}
}

// FindScoringCall retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindScoringCall(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ScoringCall, error) {
	scoringCallObj := &ScoringCall{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"scoring_call\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, scoringCallObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: unable to select from scoring_call")
	}

	if err = scoringCallObj.doAfterSelectHooks(ctx, exec); err != nil {
		return scoringCallObj, err
	}

	return scoringCallObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ScoringCall) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no scoring_call provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(scoringCallColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	scoringCallInsertCacheMut.RLock()
	cache, cached := scoringCallInsertCache[key]
	scoringCallInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			scoringCallAllColumns,
			scoringCallColumnsWithDefault,
			scoringCallColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(scoringCallType, scoringCallMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(scoringCallType, scoringCallMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"scoring_call\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"scoring_call\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "entity: unable to insert into scoring_call")
	}

	if !cached {
		scoringCallInsertCacheMut.Lock()
		scoringCallInsertCache[key] = cache
		scoringCallInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ScoringCall.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ScoringCall) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	scoringCallUpdateCacheMut.RLock()
	cache, cached := scoringCallUpdateCache[key]
	scoringCallUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			scoringCallAllColumns,
			scoringCallPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("entity: unable to update scoring_call, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"scoring_call\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, scoringCallPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(scoringCallType, scoringCallMapping, append(wl, scoringCallPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update scoring_call row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by update for scoring_call")
	}

	if !cached {
		scoringCallUpdateCacheMut.Lock()
		scoringCallUpdateCache[key] = cache
		scoringCallUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q scoringCallQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all for scoring_call")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected for scoring_call")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ScoringCallSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("entity: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scoringCallPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"scoring_call\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, scoringCallPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all in scoringCall slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected all in update all scoringCall")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ScoringCall) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("entity: no scoring_call provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(scoringCallColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	scoringCallUpsertCacheMut.RLock()
	cache, cached := scoringCallUpsertCache[key]
	scoringCallUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			scoringCallAllColumns,
			scoringCallColumnsWithDefault,
			scoringCallColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			scoringCallAllColumns,
			scoringCallPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("entity: unable to upsert scoring_call, could not build update column list")
		}

		ret := strmangle.SetComplement(scoringCallAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(scoringCallPrimaryKeyColumns) == 0 {
				return errors.New("entity: unable to upsert scoring_call, could not build conflict column list")
			}

			conflict = make([]string, len(scoringCallPrimaryKeyColumns))
			copy(conflict, scoringCallPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"scoring_call\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(scoringCallType, scoringCallMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(scoringCallType, scoringCallMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "entity: unable to upsert scoring_call")
	}

	if !cached {
		scoringCallUpsertCacheMut.Lock()
		scoringCallUpsertCache[key] = cache
		scoringCallUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ScoringCall record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ScoringCall) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("entity: no ScoringCall provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), scoringCallPrimaryKeyMapping)
	sql := "DELETE FROM \"scoring_call\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete from scoring_call")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by delete for scoring_call")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q scoringCallQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("entity: no scoringCallQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from scoring_call")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for scoring_call")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ScoringCallSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(scoringCallBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scoringCallPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"scoring_call\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, scoringCallPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from scoringCall slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for scoring_call")
	}

	if len(scoringCallAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ScoringCall) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindScoringCall(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ScoringCallSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ScoringCallSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scoringCallPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"scoring_call\".* FROM \"scoring_call\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, scoringCallPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "entity: unable to reload all in ScoringCallSlice")
	}

	*o = slice

	return nil
}

// ScoringCallExists checks if the ScoringCall row exists.
func ScoringCallExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"scoring_call\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "entity: unable to check if scoring_call exists")
	}

	return exists, nil
}

// Exists checks if the ScoringCall row exists.
func (o *ScoringCall) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ScoringCallExists(ctx, exec, o.ID)
}
