// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testScoringTexts(t *testing.T) {
	t.Parallel()

	query := ScoringTexts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testScoringTextsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ScoringTexts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testScoringTextsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ScoringTexts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ScoringTexts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testScoringTextsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ScoringTextSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ScoringTexts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testScoringTextsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ScoringTextExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ScoringText exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ScoringTextExists to return true, but got false.")
	}
}

func testScoringTextsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	scoringTextFound, err := FindScoringText(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if scoringTextFound == nil {
		t.Error("want a record, got nil")
	}
}

func testScoringTextsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ScoringTexts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testScoringTextsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ScoringTexts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testScoringTextsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	scoringTextOne := &ScoringText{}
	scoringTextTwo := &ScoringText{}
	if err = randomize.Struct(seed, scoringTextOne, scoringTextDBTypes, false, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}
	if err = randomize.Struct(seed, scoringTextTwo, scoringTextDBTypes, false, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = scoringTextOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = scoringTextTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ScoringTexts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testScoringTextsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	scoringTextOne := &ScoringText{}
	scoringTextTwo := &ScoringText{}
	if err = randomize.Struct(seed, scoringTextOne, scoringTextDBTypes, false, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}
	if err = randomize.Struct(seed, scoringTextTwo, scoringTextDBTypes, false, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = scoringTextOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = scoringTextTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ScoringTexts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func scoringTextBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ScoringText) error {
	*o = ScoringText{}
	return nil
}

func scoringTextAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ScoringText) error {
	*o = ScoringText{}
	return nil
}

func scoringTextAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ScoringText) error {
	*o = ScoringText{}
	return nil
}

func scoringTextBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ScoringText) error {
	*o = ScoringText{}
	return nil
}

func scoringTextAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ScoringText) error {
	*o = ScoringText{}
	return nil
}

func scoringTextBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ScoringText) error {
	*o = ScoringText{}
	return nil
}

func scoringTextAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ScoringText) error {
	*o = ScoringText{}
	return nil
}

func scoringTextBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ScoringText) error {
	*o = ScoringText{}
	return nil
}

func scoringTextAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ScoringText) error {
	*o = ScoringText{}
	return nil
}

func testScoringTextsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ScoringText{}
	o := &ScoringText{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, scoringTextDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ScoringText object: %s", err)
	}

	AddScoringTextHook(boil.BeforeInsertHook, scoringTextBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	scoringTextBeforeInsertHooks = []ScoringTextHook{}

	AddScoringTextHook(boil.AfterInsertHook, scoringTextAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	scoringTextAfterInsertHooks = []ScoringTextHook{}

	AddScoringTextHook(boil.AfterSelectHook, scoringTextAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	scoringTextAfterSelectHooks = []ScoringTextHook{}

	AddScoringTextHook(boil.BeforeUpdateHook, scoringTextBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	scoringTextBeforeUpdateHooks = []ScoringTextHook{}

	AddScoringTextHook(boil.AfterUpdateHook, scoringTextAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	scoringTextAfterUpdateHooks = []ScoringTextHook{}

	AddScoringTextHook(boil.BeforeDeleteHook, scoringTextBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	scoringTextBeforeDeleteHooks = []ScoringTextHook{}

	AddScoringTextHook(boil.AfterDeleteHook, scoringTextAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	scoringTextAfterDeleteHooks = []ScoringTextHook{}

	AddScoringTextHook(boil.BeforeUpsertHook, scoringTextBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	scoringTextBeforeUpsertHooks = []ScoringTextHook{}

	AddScoringTextHook(boil.AfterUpsertHook, scoringTextAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	scoringTextAfterUpsertHooks = []ScoringTextHook{}
}

func testScoringTextsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ScoringTexts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testScoringTextsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(scoringTextPrimaryKeyColumns, scoringTextColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := ScoringTexts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testScoringTextsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testScoringTextsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ScoringTextSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testScoringTextsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ScoringTexts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	scoringTextDBTypes = map[string]string{`ID`: `bigint`, `Base`: `numeric`, `PerChar`: `numeric`, `MaxPerMessage`: `numeric`, `CooldownSeconds`: `integer`, `CreatedAt`: `timestamp with time zone`}
	_                  = bytes.MinRead
)

func testScoringTextsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(scoringTextPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(scoringTextAllColumns) == len(scoringTextPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ScoringTexts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testScoringTextsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(scoringTextAllColumns) == len(scoringTextPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ScoringText{}
	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ScoringTexts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, scoringTextDBTypes, true, scoringTextPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(scoringTextAllColumns, scoringTextPrimaryKeyColumns) {
		fields = scoringTextAllColumns
	} else {
		fields = strmangle.SetComplement(
			scoringTextAllColumns,
			scoringTextPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ScoringTextSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testScoringTextsUpsert(t *testing.T) {
	t.Parallel()

	if len(scoringTextAllColumns) == len(scoringTextPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ScoringText{}
	if err = randomize.Struct(seed, &o, scoringTextDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ScoringText: %s", err)
	}

	count, err := ScoringTexts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, scoringTextDBTypes, false, scoringTextPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ScoringText struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ScoringText: %s", err)
	}

	count, err = ScoringTexts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
