// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSMSBroadcasts(t *testing.T) {
	t.Parallel()

	query := SMSBroadcasts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSMSBroadcastsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SMSBroadcasts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSMSBroadcastsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := SMSBroadcasts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SMSBroadcasts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSMSBroadcastsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SMSBroadcastSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SMSBroadcasts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSMSBroadcastsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SMSBroadcastExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if SMSBroadcast exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SMSBroadcastExists to return true, but got false.")
	}
}

func testSMSBroadcastsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	smsBroadcastFound, err := FindSMSBroadcast(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if smsBroadcastFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSMSBroadcastsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = SMSBroadcasts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSMSBroadcastsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := SMSBroadcasts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSMSBroadcastsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	smsBroadcastOne := &SMSBroadcast{}
	smsBroadcastTwo := &SMSBroadcast{}
	if err = randomize.Struct(seed, smsBroadcastOne, smsBroadcastDBTypes, false, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}
	if err = randomize.Struct(seed, smsBroadcastTwo, smsBroadcastDBTypes, false, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = smsBroadcastOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = smsBroadcastTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SMSBroadcasts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSMSBroadcastsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	smsBroadcastOne := &SMSBroadcast{}
	smsBroadcastTwo := &SMSBroadcast{}
	if err = randomize.Struct(seed, smsBroadcastOne, smsBroadcastDBTypes, false, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}
	if err = randomize.Struct(seed, smsBroadcastTwo, smsBroadcastDBTypes, false, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = smsBroadcastOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = smsBroadcastTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SMSBroadcasts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func smsBroadcastBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *SMSBroadcast) error {
	*o = SMSBroadcast{}
	return nil
}

func smsBroadcastAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *SMSBroadcast) error {
	*o = SMSBroadcast{}
	return nil
}

func smsBroadcastAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *SMSBroadcast) error {
	*o = SMSBroadcast{}
	return nil
}

func smsBroadcastBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SMSBroadcast) error {
	*o = SMSBroadcast{}
	return nil
}

func smsBroadcastAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SMSBroadcast) error {
	*o = SMSBroadcast{}
	return nil
}

func smsBroadcastBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SMSBroadcast) error {
	*o = SMSBroadcast{}
	return nil
}

func smsBroadcastAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SMSBroadcast) error {
	*o = SMSBroadcast{}
	return nil
}

func smsBroadcastBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SMSBroadcast) error {
	*o = SMSBroadcast{}
	return nil
}

func smsBroadcastAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SMSBroadcast) error {
	*o = SMSBroadcast{}
	return nil
}

func testSMSBroadcastsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &SMSBroadcast{}
	o := &SMSBroadcast{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, false); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast object: %s", err)
	}

	AddSMSBroadcastHook(boil.BeforeInsertHook, smsBroadcastBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	smsBroadcastBeforeInsertHooks = []SMSBroadcastHook{}

	AddSMSBroadcastHook(boil.AfterInsertHook, smsBroadcastAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	smsBroadcastAfterInsertHooks = []SMSBroadcastHook{}

	AddSMSBroadcastHook(boil.AfterSelectHook, smsBroadcastAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	smsBroadcastAfterSelectHooks = []SMSBroadcastHook{}

	AddSMSBroadcastHook(boil.BeforeUpdateHook, smsBroadcastBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	smsBroadcastBeforeUpdateHooks = []SMSBroadcastHook{}

	AddSMSBroadcastHook(boil.AfterUpdateHook, smsBroadcastAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	smsBroadcastAfterUpdateHooks = []SMSBroadcastHook{}

	AddSMSBroadcastHook(boil.BeforeDeleteHook, smsBroadcastBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	smsBroadcastBeforeDeleteHooks = []SMSBroadcastHook{}

	AddSMSBroadcastHook(boil.AfterDeleteHook, smsBroadcastAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	smsBroadcastAfterDeleteHooks = []SMSBroadcastHook{}

	AddSMSBroadcastHook(boil.BeforeUpsertHook, smsBroadcastBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	smsBroadcastBeforeUpsertHooks = []SMSBroadcastHook{}

	AddSMSBroadcastHook(boil.AfterUpsertHook, smsBroadcastAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	smsBroadcastAfterUpsertHooks = []SMSBroadcastHook{}
}

func testSMSBroadcastsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SMSBroadcasts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSMSBroadcastsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(smsBroadcastPrimaryKeyColumns, smsBroadcastColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := SMSBroadcasts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSMSBroadcastToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local SMSBroadcast
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, smsBroadcastDBTypes, false, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := SMSBroadcastSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*SMSBroadcast)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testSMSBroadcastToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SMSBroadcast
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, smsBroadcastDBTypes, false, strmangle.SetComplement(smsBroadcastPrimaryKeyColumns, smsBroadcastColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.SMSBroadcasts[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testSMSBroadcastsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSMSBroadcastsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SMSBroadcastSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSMSBroadcastsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SMSBroadcasts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	smsBroadcastDBTypes = map[string]string{`ID`: `uuid`, `UserID`: `uuid`, `Phone`: `text`, `Message`: `text`, `Status`: `text`, `Error`: `text`, `CreatedAt`: `timestamp with time zone`}
	_                   = bytes.MinRead
)

func testSMSBroadcastsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(smsBroadcastPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(smsBroadcastAllColumns) == len(smsBroadcastPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SMSBroadcasts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSMSBroadcastsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(smsBroadcastAllColumns) == len(smsBroadcastPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SMSBroadcast{}
	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SMSBroadcasts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, smsBroadcastDBTypes, true, smsBroadcastPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(smsBroadcastAllColumns, smsBroadcastPrimaryKeyColumns) {
		fields = smsBroadcastAllColumns
	} else {
		fields = strmangle.SetComplement(
			smsBroadcastAllColumns,
			smsBroadcastPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SMSBroadcastSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSMSBroadcastsUpsert(t *testing.T) {
	t.Parallel()

	if len(smsBroadcastAllColumns) == len(smsBroadcastPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := SMSBroadcast{}
	if err = randomize.Struct(seed, &o, smsBroadcastDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SMSBroadcast: %s", err)
	}

	count, err := SMSBroadcasts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, smsBroadcastDBTypes, false, smsBroadcastPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SMSBroadcast struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SMSBroadcast: %s", err)
	}

	count, err = SMSBroadcasts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
