// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// UserConsent is an object representing the database table.
type UserConsent struct {
	ID          string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID      string      `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	ConsentType string      `boil:"consent_type" json:"consent_type" toml:"consent_type" yaml:"consent_type"`
	Version     string      `boil:"version" json:"version" toml:"version" yaml:"version"`
	Accepted    bool        `boil:"accepted" json:"accepted" toml:"accepted" yaml:"accepted"`
	AcceptedAt  time.Time   `boil:"accepted_at" json:"accepted_at" toml:"accepted_at" yaml:"accepted_at"`
	RevokedAt   null.Time   `boil:"revoked_at" json:"revoked_at,omitempty" toml:"revoked_at" yaml:"revoked_at,omitempty"`
	IP          null.String `boil:"ip" json:"ip,omitempty" toml:"ip" yaml:"ip,omitempty"`
	UserAgent   null.String `boil:"user_agent" json:"user_agent,omitempty" toml:"user_agent" yaml:"user_agent,omitempty"`

	R *userConsentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userConsentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserConsentColumns = struct {
	ID          string
	UserID      string
	ConsentType string
	Version     string
	Accepted    string
	AcceptedAt  string
	RevokedAt   string
	IP          string
	UserAgent   string
}{
	ID:          "id",
	UserID:      "user_id",
	ConsentType: "consent_type",
	Version:     "version",
	Accepted:    "accepted",
	AcceptedAt:  "accepted_at",
	RevokedAt:   "revoked_at",
	IP:          "ip",
	UserAgent:   "user_agent",
}

var UserConsentTableColumns = struct {
	ID          string
	UserID      string
	ConsentType string
	Version     string
	Accepted    string
	AcceptedAt  string
	RevokedAt   string
	IP          string
	UserAgent   string
}{
	ID:          "user_consents.id",
	UserID:      "user_consents.user_id",
	ConsentType: "user_consents.consent_type",
	Version:     "user_consents.version",
	Accepted:    "user_consents.accepted",
	AcceptedAt:  "user_consents.accepted_at",
	RevokedAt:   "user_consents.revoked_at",
	IP:          "user_consents.ip",
	UserAgent:   "user_consents.user_agent",
}

// Generated where

var UserConsentWhere = struct {
	ID          whereHelperstring
	UserID      whereHelperstring
	ConsentType whereHelperstring
	Version     whereHelperstring
	Accepted    whereHelperbool
	AcceptedAt  whereHelpertime_Time
	RevokedAt   whereHelpernull_Time
	IP          whereHelpernull_String
	UserAgent   whereHelpernull_String
}{
	ID:          whereHelperstring{field: "\"user_consents\".\"id\""},
	UserID:      whereHelperstring{field: "\"user_consents\".\"user_id\""},
	ConsentType: whereHelperstring{field: "\"user_consents\".\"consent_type\""},
	Version:     whereHelperstring{field: "\"user_consents\".\"version\""},
	Accepted:    whereHelperbool{field: "\"user_consents\".\"accepted\""},
	AcceptedAt:  whereHelpertime_Time{field: "\"user_consents\".\"accepted_at\""},
	RevokedAt:   whereHelpernull_Time{field: "\"user_consents\".\"revoked_at\""},
	IP:          whereHelpernull_String{field: "\"user_consents\".\"ip\""},
	UserAgent:   whereHelpernull_String{field: "\"user_consents\".\"user_agent\""},
}

// UserConsentRels is where relationship names are stored.
var UserConsentRels = struct {
	User string
}{
	User: "User",
}

// userConsentR is where relationships are stored.
type userConsentR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*userConsentR) NewStruct() *userConsentR {
	return &userConsentR{}
}

func (o *UserConsent) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *userConsentR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// userConsentL is where Load methods for each relationship are stored.
type userConsentL struct{}

var (
	userConsentAllColumns            = []string{"id", "user_id", "consent_type", "version", "accepted", "accepted_at", "revoked_at", "ip", "user_agent"}
	userConsentColumnsWithoutDefault = []string{"user_id", "consent_type", "version", "accepted"}
	userConsentColumnsWithDefault    = []string{"id", "accepted_at", "revoked_at", "ip", "user_agent"}
	userConsentPrimaryKeyColumns     = []string{"id"}
	userConsentGeneratedColumns      = []string{}
)

type (
	// UserConsentSlice is an alias for a slice of pointers to UserConsent.
	// This should almost always be used instead of []UserConsent.
	UserConsentSlice []*UserConsent
	// UserConsentHook is the signature for custom UserConsent hook methods
	UserConsentHook func(context.Context, boil.ContextExecutor, *UserConsent) error

	userConsentQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userConsentType                 = reflect.TypeOf(&UserConsent{})
	userConsentMapping              = queries.MakeStructMapping(userConsentType)
	userConsentPrimaryKeyMapping, _ = queries.BindMapping(userConsentType, userConsentMapping, userConsentPrimaryKeyColumns)
	userConsentInsertCacheMut       sync.RWMutex
	userConsentInsertCache          = make(map[string]insertCache)
	userConsentUpdateCacheMut       sync.RWMutex
	userConsentUpdateCache          = make(map[string]updateCache)
	userConsentUpsertCacheMut       sync.RWMutex
	userConsentUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userConsentAfterSelectMu sync.Mutex
var userConsentAfterSelectHooks []UserConsentHook

var userConsentBeforeInsertMu sync.Mutex
var userConsentBeforeInsertHooks []UserConsentHook
var userConsentAfterInsertMu sync.Mutex
var userConsentAfterInsertHooks []UserConsentHook

var userConsentBeforeUpdateMu sync.Mutex
var userConsentBeforeUpdateHooks []UserConsentHook
var userConsentAfterUpdateMu sync.Mutex
var userConsentAfterUpdateHooks []UserConsentHook

var userConsentBeforeDeleteMu sync.Mutex
var userConsentBeforeDeleteHooks []UserConsentHook
var userConsentAfterDeleteMu sync.Mutex
var userConsentAfterDeleteHooks []UserConsentHook

var userConsentBeforeUpsertMu sync.Mutex
var userConsentBeforeUpsertHooks []UserConsentHook
var userConsentAfterUpsertMu sync.Mutex
var userConsentAfterUpsertHooks []UserConsentHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserConsent) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userConsentAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserConsent) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userConsentBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserConsent) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userConsentAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserConsent) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userConsentBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserConsent) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userConsentAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserConsent) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userConsentBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserConsent) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userConsentAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserConsent) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userConsentBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserConsent) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userConsentAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserConsentHook registers your hook function for all future operations.
func AddUserConsentHook(hookPoint boil.HookPoint, userConsentHook UserConsentHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userConsentAfterSelectMu.Lock()
		userConsentAfterSelectHooks = append(userConsentAfterSelectHooks, userConsentHook)
		userConsentAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userConsentBeforeInsertMu.Lock()
		userConsentBeforeInsertHooks = append(userConsentBeforeInsertHooks, userConsentHook)
		userConsentBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userConsentAfterInsertMu.Lock()
		userConsentAfterInsertHooks = append(userConsentAfterInsertHooks, userConsentHook)
		userConsentAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userConsentBeforeUpdateMu.Lock()
		userConsentBeforeUpdateHooks = append(userConsentBeforeUpdateHooks, userConsentHook)
		userConsentBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userConsentAfterUpdateMu.Lock()
		userConsentAfterUpdateHooks = append(userConsentAfterUpdateHooks, userConsentHook)
		userConsentAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userConsentBeforeDeleteMu.Lock()
		userConsentBeforeDeleteHooks = append(userConsentBeforeDeleteHooks, userConsentHook)
		userConsentBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userConsentAfterDeleteMu.Lock()
		userConsentAfterDeleteHooks = append(userConsentAfterDeleteHooks, userConsentHook)
		userConsentAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userConsentBeforeUpsertMu.Lock()
		userConsentBeforeUpsertHooks = append(userConsentBeforeUpsertHooks, userConsentHook)
		userConsentBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userConsentAfterUpsertMu.Lock()
		userConsentAfterUpsertHooks = append(userConsentAfterUpsertHooks, userConsentHook)
		userConsentAfterUpsertMu.Unlock()
	}
}

// One returns a single userConsent record from the query.
func (q userConsentQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserConsent, error) {
	o := &UserConsent{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: failed to execute a one query for user_consents")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserConsent records from the query.
func (q userConsentQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserConsentSlice, error) {
	var o []*UserConsent

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "entity: failed to assign all query results to UserConsent slice")
	}

	if len(userConsentAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserConsent records in the query.
func (q userConsentQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to count user_consents rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userConsentQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "entity: failed to check if user_consents exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *UserConsent) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userConsentL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserConsent interface{}, mods queries.Applicator) error {
	var slice []*UserConsent
	var object *UserConsent

	if singular {
		var ok bool
		object, ok = maybeUserConsent.(*UserConsent)
		if !ok {
			object = new(UserConsent)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserConsent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserConsent))
			}
		}
	} else {
		s, ok := maybeUserConsent.(*[]*UserConsent)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserConsent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserConsent))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userConsentR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userConsentR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserConsents = append(foreign.R.UserConsents, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserConsents = append(foreign.R.UserConsents, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the userConsent to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserConsents.
func (o *UserConsent) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_consents\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userConsentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userConsentR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserConsents: UserConsentSlice{o},
		}
	} else {
		related.R.UserConsents = append(related.R.UserConsents, o)
	}

	return nil
}

// UserConsents retrieves all the records using an executor.
func UserConsents(mods ...qm.QueryMod) userConsentQuery {
	mods = append(mods, qm.From("\"user_consents\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_consents\".*"})
	}

	return userConsentQuery{q}
}

// FindUserConsent retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserConsent(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*UserConsent, error) {
	userConsentObj := &UserConsent{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_consents\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userConsentObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: unable to select from user_consents")
	}

	if err = userConsentObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userConsentObj, err
	}

	return userConsentObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserConsent) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no user_consents provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userConsentColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userConsentInsertCacheMut.RLock()
	cache, cached := userConsentInsertCache[key]
	userConsentInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userConsentAllColumns,
			userConsentColumnsWithDefault,
			userConsentColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userConsentType, userConsentMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userConsentType, userConsentMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_consents\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_consents\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "entity: unable to insert into user_consents")
	}

	if !cached {
		userConsentInsertCacheMut.Lock()
		userConsentInsertCache[key] = cache
		userConsentInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserConsent.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserConsent) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userConsentUpdateCacheMut.RLock()
	cache, cached := userConsentUpdateCache[key]
	userConsentUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userConsentAllColumns,
			userConsentPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("entity: unable to update user_consents, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_consents\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userConsentPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userConsentType, userConsentMapping, append(wl, userConsentPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update user_consents row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by update for user_consents")
	}

	if !cached {
		userConsentUpdateCacheMut.Lock()
		userConsentUpdateCache[key] = cache
		userConsentUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userConsentQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all for user_consents")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected for user_consents")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserConsentSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("entity: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userConsentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_consents\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userConsentPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all in userConsent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected all in update all userConsent")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserConsent) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("entity: no user_consents provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userConsentColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userConsentUpsertCacheMut.RLock()
	cache, cached := userConsentUpsertCache[key]
	userConsentUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userConsentAllColumns,
			userConsentColumnsWithDefault,
			userConsentColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userConsentAllColumns,
			userConsentPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("entity: unable to upsert user_consents, could not build update column list")
		}

		ret := strmangle.SetComplement(userConsentAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userConsentPrimaryKeyColumns) == 0 {
				return errors.New("entity: unable to upsert user_consents, could not build conflict column list")
			}

			conflict = make([]string, len(userConsentPrimaryKeyColumns))
			copy(conflict, userConsentPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_consents\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userConsentType, userConsentMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userConsentType, userConsentMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "entity: unable to upsert user_consents")
	}

	if !cached {
		userConsentUpsertCacheMut.Lock()
		userConsentUpsertCache[key] = cache
		userConsentUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserConsent record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserConsent) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("entity: no UserConsent provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userConsentPrimaryKeyMapping)
	sql := "DELETE FROM \"user_consents\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete from user_consents")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by delete for user_consents")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userConsentQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("entity: no userConsentQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from user_consents")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for user_consents")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserConsentSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userConsentBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userConsentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_consents\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userConsentPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from userConsent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for user_consents")
	}

	if len(userConsentAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserConsent) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserConsent(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserConsentSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserConsentSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userConsentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_consents\".* FROM \"user_consents\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userConsentPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "entity: unable to reload all in UserConsentSlice")
	}

	*o = slice

	return nil
}

// UserConsentExists checks if the UserConsent row exists.
func UserConsentExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_consents\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "entity: unable to check if user_consents exists")
	}

	return exists, nil
}

// Exists checks if the UserConsent row exists.
func (o *UserConsent) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserConsentExists(ctx, exec, o.ID)
}
