// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// UserReport is an object representing the database table.
type UserReport struct {
	ID             string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	ReporterUserID string      `boil:"reporter_user_id" json:"reporter_user_id" toml:"reporter_user_id" yaml:"reporter_user_id"`
	ReportedUserID string      `boil:"reported_user_id" json:"reported_user_id" toml:"reported_user_id" yaml:"reported_user_id"`
	SubjectType    string      `boil:"subject_type" json:"subject_type" toml:"subject_type" yaml:"subject_type"`
	SubjectID      null.String `boil:"subject_id" json:"subject_id,omitempty" toml:"subject_id" yaml:"subject_id,omitempty"`
	Category       string      `boil:"category" json:"category" toml:"category" yaml:"category"`
	Notes          null.String `boil:"notes" json:"notes,omitempty" toml:"notes" yaml:"notes,omitempty"`
	Status         string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	Severity       null.String `boil:"severity" json:"severity,omitempty" toml:"severity" yaml:"severity,omitempty"`
	Metadata       null.JSON   `boil:"metadata" json:"metadata,omitempty" toml:"metadata" yaml:"metadata,omitempty"`
	AutoAction     null.String `boil:"auto_action" json:"auto_action,omitempty" toml:"auto_action" yaml:"auto_action,omitempty"`
	CreatedAt      time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	ResolvedAt     null.Time   `boil:"resolved_at" json:"resolved_at,omitempty" toml:"resolved_at" yaml:"resolved_at,omitempty"`

	R *userReportR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userReportL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserReportColumns = struct {
	ID             string
	ReporterUserID string
	ReportedUserID string
	SubjectType    string
	SubjectID      string
	Category       string
	Notes          string
	Status         string
	Severity       string
	Metadata       string
	AutoAction     string
	CreatedAt      string
	UpdatedAt      string
	ResolvedAt     string
}{
	ID:             "id",
	ReporterUserID: "reporter_user_id",
	ReportedUserID: "reported_user_id",
	SubjectType:    "subject_type",
	SubjectID:      "subject_id",
	Category:       "category",
	Notes:          "notes",
	Status:         "status",
	Severity:       "severity",
	Metadata:       "metadata",
	AutoAction:     "auto_action",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
	ResolvedAt:     "resolved_at",
}

var UserReportTableColumns = struct {
	ID             string
	ReporterUserID string
	ReportedUserID string
	SubjectType    string
	SubjectID      string
	Category       string
	Notes          string
	Status         string
	Severity       string
	Metadata       string
	AutoAction     string
	CreatedAt      string
	UpdatedAt      string
	ResolvedAt     string
}{
	ID:             "user_reports.id",
	ReporterUserID: "user_reports.reporter_user_id",
	ReportedUserID: "user_reports.reported_user_id",
	SubjectType:    "user_reports.subject_type",
	SubjectID:      "user_reports.subject_id",
	Category:       "user_reports.category",
	Notes:          "user_reports.notes",
	Status:         "user_reports.status",
	Severity:       "user_reports.severity",
	Metadata:       "user_reports.metadata",
	AutoAction:     "user_reports.auto_action",
	CreatedAt:      "user_reports.created_at",
	UpdatedAt:      "user_reports.updated_at",
	ResolvedAt:     "user_reports.resolved_at",
}

// Generated where

var UserReportWhere = struct {
	ID             whereHelperstring
	ReporterUserID whereHelperstring
	ReportedUserID whereHelperstring
	SubjectType    whereHelperstring
	SubjectID      whereHelpernull_String
	Category       whereHelperstring
	Notes          whereHelpernull_String
	Status         whereHelperstring
	Severity       whereHelpernull_String
	Metadata       whereHelpernull_JSON
	AutoAction     whereHelpernull_String
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
	ResolvedAt     whereHelpernull_Time
}{
	ID:             whereHelperstring{field: "\"user_reports\".\"id\""},
	ReporterUserID: whereHelperstring{field: "\"user_reports\".\"reporter_user_id\""},
	ReportedUserID: whereHelperstring{field: "\"user_reports\".\"reported_user_id\""},
	SubjectType:    whereHelperstring{field: "\"user_reports\".\"subject_type\""},
	SubjectID:      whereHelpernull_String{field: "\"user_reports\".\"subject_id\""},
	Category:       whereHelperstring{field: "\"user_reports\".\"category\""},
	Notes:          whereHelpernull_String{field: "\"user_reports\".\"notes\""},
	Status:         whereHelperstring{field: "\"user_reports\".\"status\""},
	Severity:       whereHelpernull_String{field: "\"user_reports\".\"severity\""},
	Metadata:       whereHelpernull_JSON{field: "\"user_reports\".\"metadata\""},
	AutoAction:     whereHelpernull_String{field: "\"user_reports\".\"auto_action\""},
	CreatedAt:      whereHelpertime_Time{field: "\"user_reports\".\"created_at\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"user_reports\".\"updated_at\""},
	ResolvedAt:     whereHelpernull_Time{field: "\"user_reports\".\"resolved_at\""},
}

// UserReportRels is where relationship names are stored.
var UserReportRels = struct {
	ReportedUser        string
	ReporterUser        string
	ReportReportActions string
}{
	ReportedUser:        "ReportedUser",
	ReporterUser:        "ReporterUser",
	ReportReportActions: "ReportReportActions",
}

// userReportR is where relationships are stored.
type userReportR struct {
	ReportedUser        *User             `boil:"ReportedUser" json:"ReportedUser" toml:"ReportedUser" yaml:"ReportedUser"`
	ReporterUser        *User             `boil:"ReporterUser" json:"ReporterUser" toml:"ReporterUser" yaml:"ReporterUser"`
	ReportReportActions ReportActionSlice `boil:"ReportReportActions" json:"ReportReportActions" toml:"ReportReportActions" yaml:"ReportReportActions"`
}

// NewStruct creates a new relationship struct
func (*userReportR) NewStruct() *userReportR {
	return &userReportR{}
}

func (o *UserReport) GetReportedUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetReportedUser()
}

func (r *userReportR) GetReportedUser() *User {
	if r == nil {
		return nil
	}

	return r.ReportedUser
}

func (o *UserReport) GetReporterUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetReporterUser()
}

func (r *userReportR) GetReporterUser() *User {
	if r == nil {
		return nil
	}

	return r.ReporterUser
}

func (o *UserReport) GetReportReportActions() ReportActionSlice {
	if o == nil {
		return nil
	}

	return o.R.GetReportReportActions()
}

func (r *userReportR) GetReportReportActions() ReportActionSlice {
	if r == nil {
		return nil
	}

	return r.ReportReportActions
}

// userReportL is where Load methods for each relationship are stored.
type userReportL struct{}

var (
	userReportAllColumns            = []string{"id", "reporter_user_id", "reported_user_id", "subject_type", "subject_id", "category", "notes", "status", "severity", "metadata", "auto_action", "created_at", "updated_at", "resolved_at"}
	userReportColumnsWithoutDefault = []string{"reporter_user_id", "reported_user_id", "subject_type", "category"}
	userReportColumnsWithDefault    = []string{"id", "subject_id", "notes", "status", "severity", "metadata", "auto_action", "created_at", "updated_at", "resolved_at"}
	userReportPrimaryKeyColumns     = []string{"id"}
	userReportGeneratedColumns      = []string{}
)

type (
	// UserReportSlice is an alias for a slice of pointers to UserReport.
	// This should almost always be used instead of []UserReport.
	UserReportSlice []*UserReport
	// UserReportHook is the signature for custom UserReport hook methods
	UserReportHook func(context.Context, boil.ContextExecutor, *UserReport) error

	userReportQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userReportType                 = reflect.TypeOf(&UserReport{})
	userReportMapping              = queries.MakeStructMapping(userReportType)
	userReportPrimaryKeyMapping, _ = queries.BindMapping(userReportType, userReportMapping, userReportPrimaryKeyColumns)
	userReportInsertCacheMut       sync.RWMutex
	userReportInsertCache          = make(map[string]insertCache)
	userReportUpdateCacheMut       sync.RWMutex
	userReportUpdateCache          = make(map[string]updateCache)
	userReportUpsertCacheMut       sync.RWMutex
	userReportUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userReportAfterSelectMu sync.Mutex
var userReportAfterSelectHooks []UserReportHook

var userReportBeforeInsertMu sync.Mutex
var userReportBeforeInsertHooks []UserReportHook
var userReportAfterInsertMu sync.Mutex
var userReportAfterInsertHooks []UserReportHook

var userReportBeforeUpdateMu sync.Mutex
var userReportBeforeUpdateHooks []UserReportHook
var userReportAfterUpdateMu sync.Mutex
var userReportAfterUpdateHooks []UserReportHook

var userReportBeforeDeleteMu sync.Mutex
var userReportBeforeDeleteHooks []UserReportHook
var userReportAfterDeleteMu sync.Mutex
var userReportAfterDeleteHooks []UserReportHook

var userReportBeforeUpsertMu sync.Mutex
var userReportBeforeUpsertHooks []UserReportHook
var userReportAfterUpsertMu sync.Mutex
var userReportAfterUpsertHooks []UserReportHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserReport) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userReportAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserReport) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userReportBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserReport) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userReportAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserReport) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userReportBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserReport) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userReportAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserReport) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userReportBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserReport) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userReportAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserReport) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userReportBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserReport) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userReportAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserReportHook registers your hook function for all future operations.
func AddUserReportHook(hookPoint boil.HookPoint, userReportHook UserReportHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userReportAfterSelectMu.Lock()
		userReportAfterSelectHooks = append(userReportAfterSelectHooks, userReportHook)
		userReportAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userReportBeforeInsertMu.Lock()
		userReportBeforeInsertHooks = append(userReportBeforeInsertHooks, userReportHook)
		userReportBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userReportAfterInsertMu.Lock()
		userReportAfterInsertHooks = append(userReportAfterInsertHooks, userReportHook)
		userReportAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userReportBeforeUpdateMu.Lock()
		userReportBeforeUpdateHooks = append(userReportBeforeUpdateHooks, userReportHook)
		userReportBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userReportAfterUpdateMu.Lock()
		userReportAfterUpdateHooks = append(userReportAfterUpdateHooks, userReportHook)
		userReportAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userReportBeforeDeleteMu.Lock()
		userReportBeforeDeleteHooks = append(userReportBeforeDeleteHooks, userReportHook)
		userReportBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userReportAfterDeleteMu.Lock()
		userReportAfterDeleteHooks = append(userReportAfterDeleteHooks, userReportHook)
		userReportAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userReportBeforeUpsertMu.Lock()
		userReportBeforeUpsertHooks = append(userReportBeforeUpsertHooks, userReportHook)
		userReportBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userReportAfterUpsertMu.Lock()
		userReportAfterUpsertHooks = append(userReportAfterUpsertHooks, userReportHook)
		userReportAfterUpsertMu.Unlock()
	}
}

// One returns a single userReport record from the query.
func (q userReportQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserReport, error) {
	o := &UserReport{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: failed to execute a one query for user_reports")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserReport records from the query.
func (q userReportQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserReportSlice, error) {
	var o []*UserReport

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "entity: failed to assign all query results to UserReport slice")
	}

	if len(userReportAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserReport records in the query.
func (q userReportQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to count user_reports rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userReportQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "entity: failed to check if user_reports exists")
	}

	return count > 0, nil
}

// ReportedUser pointed to by the foreign key.
func (o *UserReport) ReportedUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ReportedUserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// ReporterUser pointed to by the foreign key.
func (o *UserReport) ReporterUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ReporterUserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// ReportReportActions retrieves all the report_action's ReportActions with an executor via report_id column.
func (o *UserReport) ReportReportActions(mods ...qm.QueryMod) reportActionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"report_actions\".\"report_id\"=?", o.ID),
	)

	return ReportActions(queryMods...)
}

// LoadReportedUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userReportL) LoadReportedUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserReport interface{}, mods queries.Applicator) error {
	var slice []*UserReport
	var object *UserReport

	if singular {
		var ok bool
		object, ok = maybeUserReport.(*UserReport)
		if !ok {
			object = new(UserReport)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserReport)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserReport))
			}
		}
	} else {
		s, ok := maybeUserReport.(*[]*UserReport)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserReport)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserReport))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userReportR{}
		}
		args[object.ReportedUserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userReportR{}
			}

			args[obj.ReportedUserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ReportedUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.ReportedUserUserReports = append(foreign.R.ReportedUserUserReports, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ReportedUserID == foreign.ID {
				local.R.ReportedUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.ReportedUserUserReports = append(foreign.R.ReportedUserUserReports, local)
				break
			}
		}
	}

	return nil
}

// LoadReporterUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userReportL) LoadReporterUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserReport interface{}, mods queries.Applicator) error {
	var slice []*UserReport
	var object *UserReport

	if singular {
		var ok bool
		object, ok = maybeUserReport.(*UserReport)
		if !ok {
			object = new(UserReport)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserReport)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserReport))
			}
		}
	} else {
		s, ok := maybeUserReport.(*[]*UserReport)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserReport)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserReport))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userReportR{}
		}
		args[object.ReporterUserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userReportR{}
			}

			args[obj.ReporterUserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ReporterUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.ReporterUserUserReports = append(foreign.R.ReporterUserUserReports, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ReporterUserID == foreign.ID {
				local.R.ReporterUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.ReporterUserUserReports = append(foreign.R.ReporterUserUserReports, local)
				break
			}
		}
	}

	return nil
}

// LoadReportReportActions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (userReportL) LoadReportReportActions(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserReport interface{}, mods queries.Applicator) error {
	var slice []*UserReport
	var object *UserReport

	if singular {
		var ok bool
		object, ok = maybeUserReport.(*UserReport)
		if !ok {
			object = new(UserReport)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserReport)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserReport))
			}
		}
	} else {
		s, ok := maybeUserReport.(*[]*UserReport)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserReport)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserReport))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userReportR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userReportR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`report_actions`),
		qm.WhereIn(`report_actions.report_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load report_actions")
	}

	var resultSlice []*ReportAction
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice report_actions")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on report_actions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for report_actions")
	}

	if len(reportActionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ReportReportActions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &reportActionR{}
			}
			foreign.R.Report = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ReportID {
				local.R.ReportReportActions = append(local.R.ReportReportActions, foreign)
				if foreign.R == nil {
					foreign.R = &reportActionR{}
				}
				foreign.R.Report = local
				break
			}
		}
	}

	return nil
}

// SetReportedUser of the userReport to the related item.
// Sets o.R.ReportedUser to related.
// Adds o to related.R.ReportedUserUserReports.
func (o *UserReport) SetReportedUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_reports\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"reported_user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userReportPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ReportedUserID = related.ID
	if o.R == nil {
		o.R = &userReportR{
			ReportedUser: related,
		}
	} else {
		o.R.ReportedUser = related
	}

	if related.R == nil {
		related.R = &userR{
			ReportedUserUserReports: UserReportSlice{o},
		}
	} else {
		related.R.ReportedUserUserReports = append(related.R.ReportedUserUserReports, o)
	}

	return nil
}

// SetReporterUser of the userReport to the related item.
// Sets o.R.ReporterUser to related.
// Adds o to related.R.ReporterUserUserReports.
func (o *UserReport) SetReporterUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_reports\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"reporter_user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userReportPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ReporterUserID = related.ID
	if o.R == nil {
		o.R = &userReportR{
			ReporterUser: related,
		}
	} else {
		o.R.ReporterUser = related
	}

	if related.R == nil {
		related.R = &userR{
			ReporterUserUserReports: UserReportSlice{o},
		}
	} else {
		related.R.ReporterUserUserReports = append(related.R.ReporterUserUserReports, o)
	}

	return nil
}

// AddReportReportActions adds the given related objects to the existing relationships
// of the user_report, optionally inserting them as new records.
// Appends related to o.R.ReportReportActions.
// Sets related.R.Report appropriately.
func (o *UserReport) AddReportReportActions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ReportAction) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ReportID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"report_actions\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"report_id"}),
				strmangle.WhereClause("\"", "\"", 2, reportActionPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ReportID = o.ID
		}
	}

	if o.R == nil {
		o.R = &userReportR{
			ReportReportActions: related,
		}
	} else {
		o.R.ReportReportActions = append(o.R.ReportReportActions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &reportActionR{
				Report: o,
			}
		} else {
			rel.R.Report = o
		}
	}
	return nil
}

// UserReports retrieves all the records using an executor.
func UserReports(mods ...qm.QueryMod) userReportQuery {
	mods = append(mods, qm.From("\"user_reports\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_reports\".*"})
	}

	return userReportQuery{q}
}

// FindUserReport retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserReport(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*UserReport, error) {
	userReportObj := &UserReport{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_reports\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userReportObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: unable to select from user_reports")
	}

	if err = userReportObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userReportObj, err
	}

	return userReportObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserReport) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no user_reports provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userReportColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userReportInsertCacheMut.RLock()
	cache, cached := userReportInsertCache[key]
	userReportInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userReportAllColumns,
			userReportColumnsWithDefault,
			userReportColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userReportType, userReportMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userReportType, userReportMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_reports\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_reports\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "entity: unable to insert into user_reports")
	}

	if !cached {
		userReportInsertCacheMut.Lock()
		userReportInsertCache[key] = cache
		userReportInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserReport.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserReport) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userReportUpdateCacheMut.RLock()
	cache, cached := userReportUpdateCache[key]
	userReportUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userReportAllColumns,
			userReportPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("entity: unable to update user_reports, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_reports\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userReportPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userReportType, userReportMapping, append(wl, userReportPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update user_reports row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by update for user_reports")
	}

	if !cached {
		userReportUpdateCacheMut.Lock()
		userReportUpdateCache[key] = cache
		userReportUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userReportQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all for user_reports")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected for user_reports")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserReportSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("entity: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userReportPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_reports\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userReportPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all in userReport slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected all in update all userReport")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserReport) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("entity: no user_reports provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userReportColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userReportUpsertCacheMut.RLock()
	cache, cached := userReportUpsertCache[key]
	userReportUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userReportAllColumns,
			userReportColumnsWithDefault,
			userReportColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userReportAllColumns,
			userReportPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("entity: unable to upsert user_reports, could not build update column list")
		}

		ret := strmangle.SetComplement(userReportAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userReportPrimaryKeyColumns) == 0 {
				return errors.New("entity: unable to upsert user_reports, could not build conflict column list")
			}

			conflict = make([]string, len(userReportPrimaryKeyColumns))
			copy(conflict, userReportPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_reports\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userReportType, userReportMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userReportType, userReportMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "entity: unable to upsert user_reports")
	}

	if !cached {
		userReportUpsertCacheMut.Lock()
		userReportUpsertCache[key] = cache
		userReportUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserReport record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserReport) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("entity: no UserReport provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userReportPrimaryKeyMapping)
	sql := "DELETE FROM \"user_reports\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete from user_reports")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by delete for user_reports")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userReportQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("entity: no userReportQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from user_reports")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for user_reports")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserReportSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userReportBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userReportPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_reports\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userReportPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from userReport slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for user_reports")
	}

	if len(userReportAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserReport) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserReport(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserReportSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserReportSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userReportPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_reports\".* FROM \"user_reports\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userReportPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "entity: unable to reload all in UserReportSlice")
	}

	*o = slice

	return nil
}

// UserReportExists checks if the UserReport row exists.
func UserReportExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_reports\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "entity: unable to check if user_reports exists")
	}

	return exists, nil
}

// Exists checks if the UserReport row exists.
func (o *UserReport) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserReportExists(ctx, exec, o.ID)
}
