// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// VMatchEvent is an object representing the database table.
type VMatchEvent struct {
	ID         null.String `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	OccurredAt null.Time   `boil:"occurred_at" json:"occurred_at,omitempty" toml:"occurred_at" yaml:"occurred_at,omitempty"`
	UserID     null.String `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`
	MatchID    null.String `boil:"match_id" json:"match_id,omitempty" toml:"match_id" yaml:"match_id,omitempty"`
}

var VMatchEventColumns = struct {
	ID         string
	OccurredAt string
	UserID     string
	MatchID    string
}{
	ID:         "id",
	OccurredAt: "occurred_at",
	UserID:     "user_id",
	MatchID:    "match_id",
}

var VMatchEventTableColumns = struct {
	ID         string
	OccurredAt string
	UserID     string
	MatchID    string
}{
	ID:         "v_match_events.id",
	OccurredAt: "v_match_events.occurred_at",
	UserID:     "v_match_events.user_id",
	MatchID:    "v_match_events.match_id",
}

// Generated where

var VMatchEventWhere = struct {
	ID         whereHelpernull_String
	OccurredAt whereHelpernull_Time
	UserID     whereHelpernull_String
	MatchID    whereHelpernull_String
}{
	ID:         whereHelpernull_String{field: "\"v_match_events\".\"id\""},
	OccurredAt: whereHelpernull_Time{field: "\"v_match_events\".\"occurred_at\""},
	UserID:     whereHelpernull_String{field: "\"v_match_events\".\"user_id\""},
	MatchID:    whereHelpernull_String{field: "\"v_match_events\".\"match_id\""},
}

var (
	vMatchEventAllColumns            = []string{"id", "occurred_at", "user_id", "match_id"}
	vMatchEventColumnsWithoutDefault = []string{}
	vMatchEventColumnsWithDefault    = []string{"id", "occurred_at", "user_id", "match_id"}
	vMatchEventPrimaryKeyColumns     = []string{}
	vMatchEventGeneratedColumns      = []string{}
)

type (
	// VMatchEventSlice is an alias for a slice of pointers to VMatchEvent.
	// This should almost always be used instead of []VMatchEvent.
	VMatchEventSlice []*VMatchEvent
	// VMatchEventHook is the signature for custom VMatchEvent hook methods
	VMatchEventHook func(context.Context, boil.ContextExecutor, *VMatchEvent) error

	vMatchEventQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	vMatchEventType           = reflect.TypeOf(&VMatchEvent{})
	vMatchEventMapping        = queries.MakeStructMapping(vMatchEventType)
	vMatchEventInsertCacheMut sync.RWMutex
	vMatchEventInsertCache    = make(map[string]insertCache)
	vMatchEventUpdateCacheMut sync.RWMutex
	vMatchEventUpdateCache    = make(map[string]updateCache)
	vMatchEventUpsertCacheMut sync.RWMutex
	vMatchEventUpsertCache    = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
	// These are used in some views
	_ = fmt.Sprintln("")
	_ = reflect.Int
	_ = strings.Builder{}
	_ = sync.Mutex{}
	_ = strmangle.Plural("")
	_ = strconv.IntSize
)

var vMatchEventAfterSelectMu sync.Mutex
var vMatchEventAfterSelectHooks []VMatchEventHook

var vMatchEventBeforeInsertMu sync.Mutex
var vMatchEventBeforeInsertHooks []VMatchEventHook
var vMatchEventAfterInsertMu sync.Mutex
var vMatchEventAfterInsertHooks []VMatchEventHook

var vMatchEventBeforeUpsertMu sync.Mutex
var vMatchEventBeforeUpsertHooks []VMatchEventHook
var vMatchEventAfterUpsertMu sync.Mutex
var vMatchEventAfterUpsertHooks []VMatchEventHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *VMatchEvent) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vMatchEventAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *VMatchEvent) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vMatchEventBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *VMatchEvent) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vMatchEventAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *VMatchEvent) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vMatchEventBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *VMatchEvent) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vMatchEventAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddVMatchEventHook registers your hook function for all future operations.
func AddVMatchEventHook(hookPoint boil.HookPoint, vMatchEventHook VMatchEventHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		vMatchEventAfterSelectMu.Lock()
		vMatchEventAfterSelectHooks = append(vMatchEventAfterSelectHooks, vMatchEventHook)
		vMatchEventAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		vMatchEventBeforeInsertMu.Lock()
		vMatchEventBeforeInsertHooks = append(vMatchEventBeforeInsertHooks, vMatchEventHook)
		vMatchEventBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		vMatchEventAfterInsertMu.Lock()
		vMatchEventAfterInsertHooks = append(vMatchEventAfterInsertHooks, vMatchEventHook)
		vMatchEventAfterInsertMu.Unlock()
	case boil.BeforeUpsertHook:
		vMatchEventBeforeUpsertMu.Lock()
		vMatchEventBeforeUpsertHooks = append(vMatchEventBeforeUpsertHooks, vMatchEventHook)
		vMatchEventBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		vMatchEventAfterUpsertMu.Lock()
		vMatchEventAfterUpsertHooks = append(vMatchEventAfterUpsertHooks, vMatchEventHook)
		vMatchEventAfterUpsertMu.Unlock()
	}
}

// One returns a single vMatchEvent record from the query.
func (q vMatchEventQuery) One(ctx context.Context, exec boil.ContextExecutor) (*VMatchEvent, error) {
	o := &VMatchEvent{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: failed to execute a one query for v_match_events")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all VMatchEvent records from the query.
func (q vMatchEventQuery) All(ctx context.Context, exec boil.ContextExecutor) (VMatchEventSlice, error) {
	var o []*VMatchEvent

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "entity: failed to assign all query results to VMatchEvent slice")
	}

	if len(vMatchEventAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all VMatchEvent records in the query.
func (q vMatchEventQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to count v_match_events rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q vMatchEventQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "entity: failed to check if v_match_events exists")
	}

	return count > 0, nil
}

// VMatchEvents retrieves all the records using an executor.
func VMatchEvents(mods ...qm.QueryMod) vMatchEventQuery {
	mods = append(mods, qm.From("\"v_match_events\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"v_match_events\".*"})
	}

	return vMatchEventQuery{q}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *VMatchEvent) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no v_match_events provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vMatchEventColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	vMatchEventInsertCacheMut.RLock()
	cache, cached := vMatchEventInsertCache[key]
	vMatchEventInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			vMatchEventAllColumns,
			vMatchEventColumnsWithDefault,
			vMatchEventColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(vMatchEventType, vMatchEventMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(vMatchEventType, vMatchEventMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"v_match_events\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"v_match_events\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "entity: unable to insert into v_match_events")
	}

	if !cached {
		vMatchEventInsertCacheMut.Lock()
		vMatchEventInsertCache[key] = cache
		vMatchEventInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *VMatchEvent) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("entity: no v_match_events provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vMatchEventColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	vMatchEventUpsertCacheMut.RLock()
	cache, cached := vMatchEventUpsertCache[key]
	vMatchEventUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			vMatchEventAllColumns,
			vMatchEventColumnsWithDefault,
			vMatchEventColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			vMatchEventAllColumns,
			vMatchEventPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("entity: unable to upsert v_match_events, could not build update column list")
		}

		ret := strmangle.SetComplement(vMatchEventAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(vMatchEventPrimaryKeyColumns) == 0 {
				return errors.New("entity: unable to upsert v_match_events, could not build conflict column list")
			}

			conflict = make([]string, len(vMatchEventPrimaryKeyColumns))
			copy(conflict, vMatchEventPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"v_match_events\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(vMatchEventType, vMatchEventMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(vMatchEventType, vMatchEventMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "entity: unable to upsert v_match_events")
	}

	if !cached {
		vMatchEventUpsertCacheMut.Lock()
		vMatchEventUpsertCache[key] = cache
		vMatchEventUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
