// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testVerificationAttempts(t *testing.T) {
	t.Parallel()

	query := VerificationAttempts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testVerificationAttemptsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := VerificationAttempts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVerificationAttemptsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := VerificationAttempts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := VerificationAttempts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVerificationAttemptsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := VerificationAttemptSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := VerificationAttempts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVerificationAttemptsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := VerificationAttemptExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if VerificationAttempt exists: %s", err)
	}
	if !e {
		t.Errorf("Expected VerificationAttemptExists to return true, but got false.")
	}
}

func testVerificationAttemptsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	verificationAttemptFound, err := FindVerificationAttempt(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if verificationAttemptFound == nil {
		t.Error("want a record, got nil")
	}
}

func testVerificationAttemptsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = VerificationAttempts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testVerificationAttemptsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := VerificationAttempts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testVerificationAttemptsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	verificationAttemptOne := &VerificationAttempt{}
	verificationAttemptTwo := &VerificationAttempt{}
	if err = randomize.Struct(seed, verificationAttemptOne, verificationAttemptDBTypes, false, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}
	if err = randomize.Struct(seed, verificationAttemptTwo, verificationAttemptDBTypes, false, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = verificationAttemptOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = verificationAttemptTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := VerificationAttempts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testVerificationAttemptsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	verificationAttemptOne := &VerificationAttempt{}
	verificationAttemptTwo := &VerificationAttempt{}
	if err = randomize.Struct(seed, verificationAttemptOne, verificationAttemptDBTypes, false, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}
	if err = randomize.Struct(seed, verificationAttemptTwo, verificationAttemptDBTypes, false, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = verificationAttemptOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = verificationAttemptTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VerificationAttempts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func verificationAttemptBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *VerificationAttempt) error {
	*o = VerificationAttempt{}
	return nil
}

func verificationAttemptAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *VerificationAttempt) error {
	*o = VerificationAttempt{}
	return nil
}

func verificationAttemptAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *VerificationAttempt) error {
	*o = VerificationAttempt{}
	return nil
}

func verificationAttemptBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *VerificationAttempt) error {
	*o = VerificationAttempt{}
	return nil
}

func verificationAttemptAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *VerificationAttempt) error {
	*o = VerificationAttempt{}
	return nil
}

func verificationAttemptBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *VerificationAttempt) error {
	*o = VerificationAttempt{}
	return nil
}

func verificationAttemptAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *VerificationAttempt) error {
	*o = VerificationAttempt{}
	return nil
}

func verificationAttemptBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *VerificationAttempt) error {
	*o = VerificationAttempt{}
	return nil
}

func verificationAttemptAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *VerificationAttempt) error {
	*o = VerificationAttempt{}
	return nil
}

func testVerificationAttemptsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &VerificationAttempt{}
	o := &VerificationAttempt{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, false); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt object: %s", err)
	}

	AddVerificationAttemptHook(boil.BeforeInsertHook, verificationAttemptBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	verificationAttemptBeforeInsertHooks = []VerificationAttemptHook{}

	AddVerificationAttemptHook(boil.AfterInsertHook, verificationAttemptAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	verificationAttemptAfterInsertHooks = []VerificationAttemptHook{}

	AddVerificationAttemptHook(boil.AfterSelectHook, verificationAttemptAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	verificationAttemptAfterSelectHooks = []VerificationAttemptHook{}

	AddVerificationAttemptHook(boil.BeforeUpdateHook, verificationAttemptBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	verificationAttemptBeforeUpdateHooks = []VerificationAttemptHook{}

	AddVerificationAttemptHook(boil.AfterUpdateHook, verificationAttemptAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	verificationAttemptAfterUpdateHooks = []VerificationAttemptHook{}

	AddVerificationAttemptHook(boil.BeforeDeleteHook, verificationAttemptBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	verificationAttemptBeforeDeleteHooks = []VerificationAttemptHook{}

	AddVerificationAttemptHook(boil.AfterDeleteHook, verificationAttemptAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	verificationAttemptAfterDeleteHooks = []VerificationAttemptHook{}

	AddVerificationAttemptHook(boil.BeforeUpsertHook, verificationAttemptBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	verificationAttemptBeforeUpsertHooks = []VerificationAttemptHook{}

	AddVerificationAttemptHook(boil.AfterUpsertHook, verificationAttemptAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	verificationAttemptAfterUpsertHooks = []VerificationAttemptHook{}
}

func testVerificationAttemptsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VerificationAttempts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testVerificationAttemptsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(verificationAttemptPrimaryKeyColumns, verificationAttemptColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := VerificationAttempts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testVerificationAttemptToManyLastAttemptUserVerificationStatuses(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a VerificationAttempt
	var b, c UserVerificationStatus

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, userVerificationStatusDBTypes, false, userVerificationStatusColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userVerificationStatusDBTypes, false, userVerificationStatusColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.LastAttemptID, a.ID)
	queries.Assign(&c.LastAttemptID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.LastAttemptUserVerificationStatuses().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.LastAttemptID, b.LastAttemptID) {
			bFound = true
		}
		if queries.Equal(v.LastAttemptID, c.LastAttemptID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := VerificationAttemptSlice{&a}
	if err = a.L.LoadLastAttemptUserVerificationStatuses(ctx, tx, false, (*[]*VerificationAttempt)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.LastAttemptUserVerificationStatuses); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.LastAttemptUserVerificationStatuses = nil
	if err = a.L.LoadLastAttemptUserVerificationStatuses(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.LastAttemptUserVerificationStatuses); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testVerificationAttemptToManyAddOpLastAttemptUserVerificationStatuses(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a VerificationAttempt
	var b, c, d, e UserVerificationStatus

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, verificationAttemptDBTypes, false, strmangle.SetComplement(verificationAttemptPrimaryKeyColumns, verificationAttemptColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*UserVerificationStatus{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, userVerificationStatusDBTypes, false, strmangle.SetComplement(userVerificationStatusPrimaryKeyColumns, userVerificationStatusColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*UserVerificationStatus{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddLastAttemptUserVerificationStatuses(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.LastAttemptID) {
			t.Error("foreign key was wrong value", a.ID, first.LastAttemptID)
		}
		if !queries.Equal(a.ID, second.LastAttemptID) {
			t.Error("foreign key was wrong value", a.ID, second.LastAttemptID)
		}

		if first.R.LastAttempt != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.LastAttempt != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.LastAttemptUserVerificationStatuses[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.LastAttemptUserVerificationStatuses[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.LastAttemptUserVerificationStatuses().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testVerificationAttemptToManySetOpLastAttemptUserVerificationStatuses(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a VerificationAttempt
	var b, c, d, e UserVerificationStatus

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, verificationAttemptDBTypes, false, strmangle.SetComplement(verificationAttemptPrimaryKeyColumns, verificationAttemptColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*UserVerificationStatus{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, userVerificationStatusDBTypes, false, strmangle.SetComplement(userVerificationStatusPrimaryKeyColumns, userVerificationStatusColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetLastAttemptUserVerificationStatuses(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.LastAttemptUserVerificationStatuses().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetLastAttemptUserVerificationStatuses(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.LastAttemptUserVerificationStatuses().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.LastAttemptID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.LastAttemptID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.LastAttemptID) {
		t.Error("foreign key was wrong value", a.ID, d.LastAttemptID)
	}
	if !queries.Equal(a.ID, e.LastAttemptID) {
		t.Error("foreign key was wrong value", a.ID, e.LastAttemptID)
	}

	if b.R.LastAttempt != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.LastAttempt != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.LastAttempt != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.LastAttempt != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.LastAttemptUserVerificationStatuses[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.LastAttemptUserVerificationStatuses[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testVerificationAttemptToManyRemoveOpLastAttemptUserVerificationStatuses(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a VerificationAttempt
	var b, c, d, e UserVerificationStatus

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, verificationAttemptDBTypes, false, strmangle.SetComplement(verificationAttemptPrimaryKeyColumns, verificationAttemptColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*UserVerificationStatus{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, userVerificationStatusDBTypes, false, strmangle.SetComplement(userVerificationStatusPrimaryKeyColumns, userVerificationStatusColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddLastAttemptUserVerificationStatuses(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.LastAttemptUserVerificationStatuses().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveLastAttemptUserVerificationStatuses(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.LastAttemptUserVerificationStatuses().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.LastAttemptID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.LastAttemptID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.LastAttempt != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.LastAttempt != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.LastAttempt != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.LastAttempt != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.LastAttemptUserVerificationStatuses) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.LastAttemptUserVerificationStatuses[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.LastAttemptUserVerificationStatuses[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testVerificationAttemptToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local VerificationAttempt
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, verificationAttemptDBTypes, false, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := VerificationAttemptSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*VerificationAttempt)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testVerificationAttemptToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a VerificationAttempt
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, verificationAttemptDBTypes, false, strmangle.SetComplement(verificationAttemptPrimaryKeyColumns, verificationAttemptColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.VerificationAttempts[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testVerificationAttemptsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testVerificationAttemptsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := VerificationAttemptSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testVerificationAttemptsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := VerificationAttempts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	verificationAttemptDBTypes = map[string]string{`ID`: `uuid`, `UserID`: `uuid`, `Type`: `enum.verification_type('photo')`, `Status`: `enum.verification_status('pending','passed','failed','needs_review')`, `SessionID`: `text`, `LivenessScore`: `double precision`, `MatchScore`: `double precision`, `ReasonCodes`: `jsonb`, `BestFrameS3Key`: `text`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`, `ClientToken`: `text`}
	_                          = bytes.MinRead
)

func testVerificationAttemptsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(verificationAttemptPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(verificationAttemptAllColumns) == len(verificationAttemptPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VerificationAttempts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testVerificationAttemptsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(verificationAttemptAllColumns) == len(verificationAttemptPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &VerificationAttempt{}
	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VerificationAttempts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, verificationAttemptDBTypes, true, verificationAttemptPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(verificationAttemptAllColumns, verificationAttemptPrimaryKeyColumns) {
		fields = verificationAttemptAllColumns
	} else {
		fields = strmangle.SetComplement(
			verificationAttemptAllColumns,
			verificationAttemptPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := VerificationAttemptSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testVerificationAttemptsUpsert(t *testing.T) {
	t.Parallel()

	if len(verificationAttemptAllColumns) == len(verificationAttemptPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := VerificationAttempt{}
	if err = randomize.Struct(seed, &o, verificationAttemptDBTypes, true); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert VerificationAttempt: %s", err)
	}

	count, err := VerificationAttempts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, verificationAttemptDBTypes, false, verificationAttemptPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize VerificationAttempt struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert VerificationAttempt: %s", err)
	}

	count, err = VerificationAttempts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
