-- +goose Up
-- Seed ISO‑639‑1 languages (code, label).
-- Safe to run multiple times.
INSERT INTO languages (code, label) VALUES
                                        ('en', 'English'),
                                        ('es', 'Spanish'),
                                        ('fr', 'French'),
                                        ('de', 'German'),
                                        ('it', 'Italian'),
                                        ('pt', 'Portuguese'),
                                        ('ru', 'Russian'),
                                        ('ar', 'Arabic'),
                                        ('zh', 'Chinese'),
                                        ('ja', 'Japanese'),
                                        ('ko', 'Korean'),
                                        ('hi', 'Hindi'),
                                        ('bn', 'Bengali'),
                                        ('ur', 'Urdu'),
                                        ('fa', 'Persian'),
                                        ('tr', 'Turkish'),
                                        ('vi', 'Vietnamese'),
                                        ('th', 'Thai'),
                                        ('id', 'Indonesian'),
                                        ('ms', 'Malay'),
                                        ('ta', 'Tamil'),
                                        ('te', 'Telugu'),
                                        ('ml', 'Malayalam'),
                                        ('mr', 'Marathi'),
                                        ('gu', 'Gujarati'),
                                        ('kn', 'Kannada'),
                                        ('pa', 'Punjabi'),
                                        ('or', 'Odia'),
                                        ('as', 'Assamese'),
                                        ('ne', 'Nepali'),
                                        ('my', 'Burmese'),
                                        ('km', 'Khmer'),
                                        ('si', 'Sinhala'),
                                        ('he', 'Hebrew'),
                                        ('el', 'Greek'),
                                        ('nl', 'Dutch'),
                                        ('pl', 'Polish'),
                                        ('sv', 'Swedish'),
                                        ('no', 'Norwegian'),
                                        ('da', 'Danish'),
                                        ('fi', 'Finnish'),
                                        ('cs', 'Czech'),
                                        ('sk', 'Slovak'),
                                        ('sl', 'Slovenian'),
                                        ('hu', 'Hungarian'),
                                        ('ro', 'Romanian'),
                                        ('bg', 'Bulgarian'),
                                        ('uk', 'Ukrainian'),
                                        ('sr', 'Serbian'),
                                        ('hr', 'Croatian'),
                                        ('lt', 'Lithuanian'),
                                        ('lv', 'Latvian'),
                                        ('et', 'Estonian'),
                                        ('is', 'Icelandic'),
                                        ('ga', 'Irish'),
                                        ('sw', 'Swahili'),
                                        ('zu', 'Zulu'),
                                        ('yo', 'Yoruba'),
                                        ('ha', 'Hausa')
    ON CONFLICT (code) DO NOTHING;

-- +goose Down
-- Remove only the rows we inserted above.
DELETE FROM languages
WHERE code IN (
               'en','es','fr','de','it','pt','ru','ar','zh','ja','ko','hi','bn','ur','fa','tr','vi','th',
               'id','ms','ta','te','ml','mr','gu','kn','pa','or','as','ne','my','km','si','he','el','nl',
               'pl','sv','no','da','fi','cs','sk','sl','hu','ro','bg','uk','sr','hr','lt','lv','et','is',
               'ga','sw','zu','yo','ha'
    );