-- +goose Up
-- Re-seed compatibility question packs from docs/business/question-packs-content-spec.md
-- 11 categories (predictive-strength order), 40 questions, 157 answer options.

DELETE FROM user_answers;
DELETE FROM questions;
DELETE FROM question_categories;

INSERT INTO question_categories (key, name) VALUES
  ('kids_family', 'Kids & Family'),
  ('relationship_intent', 'Relationship Intent'),
  ('monogamy_boundaries', 'Monogamy & Intimacy'),
  ('faith_values', 'Faith'),
  ('money_work', 'Money & Finances'),
  ('conflict_communication', 'Conflict & Communication'),
  ('temperament_emotional_health', 'Temperament & Emotional Health'),
  ('substances', 'Substances'),
  ('time_ambition', 'Openness & Ambition'),
  ('politics_tolerance', 'Politics & Worldview'),
  ('lifestyle_cleanliness', 'Lifestyle');

WITH c AS (SELECT id, key FROM question_categories)
INSERT INTO questions (category_id, text, type, is_active, sort_order)
SELECT c.id, q.text, 'structured', TRUE, q.sort_order
FROM (VALUES
  ('kids_family', 'Do you want children?', 1),
  ('kids_family', 'Do you have children, and how do you feel about dating someone who does?', 2),
  ('kids_family', 'If you want children, what''s your rough timeline?', 3),
  ('kids_family', 'How important is closeness with extended family?', 4),
  ('kids_family', 'How should parenting roles be divided?', 5),
  ('kids_family', 'In a committed relationship, how do you see roles and responsibilities at home?', 6),
  ('relationship_intent', 'What are you looking for in a relationship right now?', 1),
  ('relationship_intent', 'How do you feel about marriage?', 2),
  ('relationship_intent', 'Would you relocate for the right relationship?', 3),
  ('relationship_intent', 'Where do you see yourself building a life long-term?', 4),
  ('monogamy_boundaries', 'What relationship structure do you want?', 1),
  ('monogamy_boundaries', 'Where are your boundaries around flirting or outside attention?', 2),
  ('monogamy_boundaries', 'How important is sexual compatibility to you?', 3),
  ('monogamy_boundaries', 'How comfortable are you openly discussing sexual needs with a partner?', 4),
  ('faith_values', 'How important is faith or religion in your life?', 1),
  ('faith_values', 'Do you need a partner who shares your faith or practices?', 2),
  ('money_work', 'Saver or spender — how do you relate to money?', 1),
  ('money_work', 'How do you feel about debt and financial risk?', 2),
  ('money_work', 'How would you prefer to handle finances in a relationship?', 3),
  ('money_work', 'When you and a partner disagree about money, how do you handle it?', 4),
  ('money_work', 'How do you feel about splitting expenses in a relationship?', 5),
  ('money_work', 'How ambitious are your long-term financial goals (e.g. owning a home, building wealth)?', 6),
  ('conflict_communication', 'What''s your default conflict style?', 1),
  ('conflict_communication', 'When you''re upset, do you need space or to talk it out right away?', 2),
  ('conflict_communication', 'When criticised by a partner, how do you usually react?', 3),
  ('conflict_communication', 'After a fight, how easily do you take responsibility and repair?', 4),
  ('conflict_communication', 'How open are you to couples therapy or working on a relationship?', 5),
  ('temperament_emotional_health', 'How easily are you thrown off by stress or strong emotions?', 1),
  ('temperament_emotional_health', 'How comfortable are you with closeness and depending on a partner?', 2),
  ('temperament_emotional_health', 'How do you react when a partner needs space or independence?', 3),
  ('substances', 'Do you drink alcohol?', 1),
  ('substances', 'Do you smoke or vape?', 2),
  ('substances', 'What is your view on recreational cannabis?', 3),
  ('substances', 'What is your view on other recreational drugs?', 4),
  ('time_ambition', 'How drawn are you to novelty and adventure vs routine and familiarity?', 1),
  ('time_ambition', 'How important are your own goals and hobbies outside the relationship?', 2),
  ('time_ambition', 'How important is career ambition to you?', 3),
  ('politics_tolerance', 'Could you be with someone with very different political views?', 1),
  ('politics_tolerance', 'How central are politics and worldview to your day-to-day life?', 2),
  ('lifestyle_cleanliness', 'How important is fitness and health in your lifestyle?', 1)
) AS q(category_key, text, sort_order)
JOIN c ON c.key = q.category_key;

WITH q AS (SELECT id, text FROM questions)
INSERT INTO question_answers (question_id, label, sort)
SELECT q.id, a.label, a.sort
FROM q JOIN (VALUES
  ('Do you want children?', 'Yes, I want children', 1),
  ('Do you want children?', 'Maybe / unsure', 2),
  ('Do you want children?', 'No, I don''t want children', 3),
  ('Do you have children, and how do you feel about dating someone who does?', 'I have children — open to a partner with or without', 1),
  ('Do you have children, and how do you feel about dating someone who does?', 'I have children — prefer a partner without children', 2),
  ('Do you have children, and how do you feel about dating someone who does?', 'No children — open to a partner with children', 3),
  ('Do you have children, and how do you feel about dating someone who does?', 'No children — prefer a partner without children', 4),
  ('If you want children, what''s your rough timeline?', 'Within 1–2 years', 1),
  ('If you want children, what''s your rough timeline?', 'In 3–5 years', 2),
  ('If you want children, what''s your rough timeline?', '5+ years', 3),
  ('If you want children, what''s your rough timeline?', 'Not sure / no timeline', 4),
  ('How important is closeness with extended family?', 'Very important', 1),
  ('How important is closeness with extended family?', 'Somewhat important', 2),
  ('How important is closeness with extended family?', 'Not very important', 3),
  ('How important is closeness with extended family?', 'Not important', 4),
  ('How should parenting roles be divided?', 'Traditional roles', 1),
  ('How should parenting roles be divided?', 'Flexible — mix of both', 2),
  ('How should parenting roles be divided?', 'Fully shared / equal split', 3),
  ('In a committed relationship, how do you see roles and responsibilities at home?', 'Traditional — clearly separate roles', 1),
  ('In a committed relationship, how do you see roles and responsibilities at home?', 'Mostly traditional', 2),
  ('In a committed relationship, how do you see roles and responsibilities at home?', 'Mostly shared / equal', 3),
  ('In a committed relationship, how do you see roles and responsibilities at home?', 'Fully shared — we split everything equally', 4),
  ('What are you looking for in a relationship right now?', 'Marriage-minded / long-term commitment', 1),
  ('What are you looking for in a relationship right now?', 'Serious relationship, open to where it leads', 2),
  ('What are you looking for in a relationship right now?', 'Casual / short-term', 3),
  ('What are you looking for in a relationship right now?', 'Still figuring it out', 4),
  ('How do you feel about marriage?', 'I want to get married', 1),
  ('How do you feel about marriage?', 'Open to marriage', 2),
  ('How do you feel about marriage?', 'Unsure', 3),
  ('How do you feel about marriage?', 'Not interested in marriage', 4),
  ('Would you relocate for the right relationship?', 'Yes', 1),
  ('Would you relocate for the right relationship?', 'Maybe — depends on circumstances', 2),
  ('Would you relocate for the right relationship?', 'No', 3),
  ('Where do you see yourself building a life long-term?', 'Big city', 1),
  ('Where do you see yourself building a life long-term?', 'Suburb or small town', 2),
  ('Where do you see yourself building a life long-term?', 'Rural / countryside', 3),
  ('Where do you see yourself building a life long-term?', 'No strong preference', 4),
  ('What relationship structure do you want?', 'Strictly monogamous', 1),
  ('What relationship structure do you want?', 'Monogamous with some flexibility', 2),
  ('What relationship structure do you want?', 'Open / ethically non-monogamous', 3),
  ('What relationship structure do you want?', 'Polyamorous / multi-partner', 4),
  ('Where are your boundaries around flirting or outside attention?', 'Not acceptable', 1),
  ('Where are your boundaries around flirting or outside attention?', 'Light flirting is fine', 2),
  ('Where are your boundaries around flirting or outside attention?', 'Depends on context', 3),
  ('Where are your boundaries around flirting or outside attention?', 'Generally fine', 4),
  ('How important is sexual compatibility to you?', 'Very important', 1),
  ('How important is sexual compatibility to you?', 'Somewhat important', 2),
  ('How important is sexual compatibility to you?', 'Nice but not essential', 3),
  ('How important is sexual compatibility to you?', 'Not a priority', 4),
  ('How comfortable are you openly discussing sexual needs with a partner?', 'Very comfortable', 1),
  ('How comfortable are you openly discussing sexual needs with a partner?', 'Somewhat comfortable', 2),
  ('How comfortable are you openly discussing sexual needs with a partner?', 'Uncomfortable but willing', 3),
  ('How comfortable are you openly discussing sexual needs with a partner?', 'Prefer not to discuss', 4),
  ('How important is faith or religion in your life?', 'Central to my life', 1),
  ('How important is faith or religion in your life?', 'Important but balanced', 2),
  ('How important is faith or religion in your life?', 'Cultural / occasional', 3),
  ('How important is faith or religion in your life?', 'Not important', 4),
  ('Do you need a partner who shares your faith or practices?', 'Yes — must share my faith', 1),
  ('Do you need a partner who shares your faith or practices?', 'Prefer shared faith but flexible', 2),
  ('Do you need a partner who shares your faith or practices?', 'Faith doesn''t need to match', 3),
  ('Do you need a partner who shares your faith or practices?', 'Not applicable — faith isn''t important to me', 4),
  ('Saver or spender — how do you relate to money?', 'I''m a saver', 1),
  ('Saver or spender — how do you relate to money?', 'More saver than spender', 2),
  ('Saver or spender — how do you relate to money?', 'More spender than saver', 3),
  ('Saver or spender — how do you relate to money?', 'I''m a spender', 4),
  ('How do you feel about debt and financial risk?', 'Avoid debt — very cautious', 1),
  ('How do you feel about debt and financial risk?', 'Some debt is OK if managed', 2),
  ('How do you feel about debt and financial risk?', 'Comfortable with moderate risk', 3),
  ('How do you feel about debt and financial risk?', 'Comfortable taking financial risks', 4),
  ('How would you prefer to handle finances in a relationship?', 'Fully joint accounts', 1),
  ('How would you prefer to handle finances in a relationship?', 'Mostly joint with some separate', 2),
  ('How would you prefer to handle finances in a relationship?', 'Mostly separate with shared expenses', 3),
  ('How would you prefer to handle finances in a relationship?', 'Fully separate', 4),
  ('When you and a partner disagree about money, how do you handle it?', 'Talk it through calmly until resolved', 1),
  ('When you and a partner disagree about money, how do you handle it?', 'Take space, then discuss', 2),
  ('When you and a partner disagree about money, how do you handle it?', 'Avoid the topic when possible', 3),
  ('When you and a partner disagree about money, how do you handle it?', 'Argue or shut down', 4),
  ('How do you feel about splitting expenses in a relationship?', '50/50 split', 1),
  ('How do you feel about splitting expenses in a relationship?', 'Proportional to income', 2),
  ('How do you feel about splitting expenses in a relationship?', 'One partner covers more', 3),
  ('How do you feel about splitting expenses in a relationship?', 'Flexible — case by case', 4),
  ('How ambitious are your long-term financial goals (e.g. owning a home, building wealth)?', 'Very — ownership / building wealth is a priority', 1),
  ('How ambitious are your long-term financial goals (e.g. owning a home, building wealth)?', 'Moderately — steady progress matters', 2),
  ('How ambitious are your long-term financial goals (e.g. owning a home, building wealth)?', 'Not very — comfort matters more than growth', 3),
  ('How ambitious are your long-term financial goals (e.g. owning a home, building wealth)?', 'I don''t set long-term financial goals', 4),
  ('What''s your default conflict style?', 'Address it directly', 1),
  ('What''s your default conflict style?', 'Collaborate and find compromise', 2),
  ('What''s your default conflict style?', 'Need time before discussing', 3),
  ('What''s your default conflict style?', 'Avoid or withdraw', 4),
  ('When you''re upset, do you need space or to talk it out right away?', 'Need space first', 1),
  ('When you''re upset, do you need space or to talk it out right away?', 'Mix — depends on the situation', 2),
  ('When you''re upset, do you need space or to talk it out right away?', 'Want to talk it out right away', 3),
  ('When you''re upset, do you need space or to talk it out right away?', 'Prefer not to discuss it', 4),
  ('When criticised by a partner, how do you usually react?', 'Listen and reflect on the feedback', 1),
  ('When criticised by a partner, how do you usually react?', 'Get defensive but try to hear them', 2),
  ('When criticised by a partner, how do you usually react?', 'Push back or argue', 3),
  ('When criticised by a partner, how do you usually react?', 'Shut down or withdraw', 4),
  ('After a fight, how easily do you take responsibility and repair?', 'I apologise and repair quickly', 1),
  ('After a fight, how easily do you take responsibility and repair?', 'I need time but will repair eventually', 2),
  ('After a fight, how easily do you take responsibility and repair?', 'I struggle to apologise first', 3),
  ('After a fight, how easily do you take responsibility and repair?', 'I rarely initiate repair', 4),
  ('How open are you to couples therapy or working on a relationship?', 'Very open', 1),
  ('How open are you to couples therapy or working on a relationship?', 'Open if needed', 2),
  ('How open are you to couples therapy or working on a relationship?', 'Unlikely but not closed off', 3),
  ('How open are you to couples therapy or working on a relationship?', 'Not interested', 4),
  ('How easily are you thrown off by stress or strong emotions?', 'I stay calm under pressure', 1),
  ('How easily are you thrown off by stress or strong emotions?', 'I recover fairly quickly', 2),
  ('How easily are you thrown off by stress or strong emotions?', 'It affects me for a while', 3),
  ('How easily are you thrown off by stress or strong emotions?', 'I get overwhelmed easily', 4),
  ('How comfortable are you with closeness and depending on a partner?', 'Very comfortable with closeness', 1),
  ('How comfortable are you with closeness and depending on a partner?', 'Comfortable with some independence', 2),
  ('How comfortable are you with closeness and depending on a partner?', 'I value a lot of independence', 3),
  ('How comfortable are you with closeness and depending on a partner?', 'Closeness makes me uneasy', 4),
  ('How do you react when a partner needs space or independence?', 'I give space easily', 1),
  ('How do you react when a partner needs space or independence?', 'A little uneasy but I manage', 2),
  ('How do you react when a partner needs space or independence?', 'I find it hard — it makes me anxious', 3),
  ('How do you react when a partner needs space or independence?', 'I struggle and need reassurance', 4),
  ('Do you drink alcohol?', 'Never', 1),
  ('Do you drink alcohol?', 'Occasionally / socially', 2),
  ('Do you drink alcohol?', 'Regularly', 3),
  ('Do you drink alcohol?', 'Frequently', 4),
  ('Do you smoke or vape?', 'Yes', 1),
  ('Do you smoke or vape?', 'Occasionally', 2),
  ('Do you smoke or vape?', 'Used to — not anymore', 3),
  ('Do you smoke or vape?', 'No', 4),
  ('What is your view on recreational cannabis?', 'I use it / fine with it', 1),
  ('What is your view on recreational cannabis?', 'OK in moderation', 2),
  ('What is your view on recreational cannabis?', 'Prefer partner doesn''t use', 3),
  ('What is your view on recreational cannabis?', 'Not OK with it', 4),
  ('What is your view on other recreational drugs?', 'OK with occasional use', 1),
  ('What is your view on other recreational drugs?', 'Depends on the substance', 2),
  ('What is your view on other recreational drugs?', 'Not OK with use', 3),
  ('What is your view on other recreational drugs?', 'Hard no — dealbreaker', 4),
  ('How drawn are you to novelty and adventure vs routine and familiarity?', 'Strongly prefer novelty and adventure', 1),
  ('How drawn are you to novelty and adventure vs routine and familiarity?', 'Lean toward adventure', 2),
  ('How drawn are you to novelty and adventure vs routine and familiarity?', 'Lean toward routine and familiarity', 3),
  ('How drawn are you to novelty and adventure vs routine and familiarity?', 'Strongly prefer routine and familiarity', 4),
  ('How important are your own goals and hobbies outside the relationship?', 'Very important', 1),
  ('How important are your own goals and hobbies outside the relationship?', 'Somewhat important', 2),
  ('How important are your own goals and hobbies outside the relationship?', 'Nice to have', 3),
  ('How important are your own goals and hobbies outside the relationship?', 'Not very important', 4),
  ('How important is career ambition to you?', 'Very important', 1),
  ('How important is career ambition to you?', 'Somewhat important', 2),
  ('How important is career ambition to you?', 'Moderate', 3),
  ('How important is career ambition to you?', 'Not a priority', 4),
  ('Could you be with someone with very different political views?', 'Yes', 1),
  ('Could you be with someone with very different political views?', 'Maybe — depends on the issues', 2),
  ('Could you be with someone with very different political views?', 'Probably not', 3),
  ('Could you be with someone with very different political views?', 'No', 4),
  ('How central are politics and worldview to your day-to-day life?', 'Very central', 1),
  ('How central are politics and worldview to your day-to-day life?', 'Somewhat central', 2),
  ('How central are politics and worldview to your day-to-day life?', 'Rarely think about it', 3),
  ('How central are politics and worldview to your day-to-day life?', 'Not important to me', 4),
  ('How important is fitness and health in your lifestyle?', 'Very important — daily focus', 1),
  ('How important is fitness and health in your lifestyle?', 'Somewhat important', 2),
  ('How important is fitness and health in your lifestyle?', 'Casual — when I can', 3),
  ('How important is fitness and health in your lifestyle?', 'Not a focus', 4)
) AS a(text, label, sort) ON q.text = a.text;

-- +goose Down
-- Restore original 10-pack / 50-question seed from 20251022211336_create_matching_schema_and_seed.sql

DELETE FROM user_answers;
DELETE FROM questions;
DELETE FROM question_categories;

INSERT INTO question_categories (key, name) VALUES
                                               ('faith_values',            'Faith & Values'),
                                               ('relationship_intent',     'Relationship Intent'),
                                               ('kids_family',             'Kids & Family'),
                                               ('monogamy_boundaries',     'Monogamy & Boundaries'),
                                               ('lifestyle_cleanliness',   'Lifestyle & Cleanliness'),
                                               ('substances',              'Substances'),
                                               ('money_work',              'Money & Work'),
                                               ('politics_tolerance',      'Politics & Tolerance'),
                                               ('conflict_communication',  'Conflict & Communication'),
                                               ('time_ambition',           'Time & Ambition');

WITH c AS (SELECT id, key FROM question_categories)
INSERT INTO questions (category_id, text, type, is_active, sort_order)
SELECT c.id, q.text, 'structured', TRUE, q.sort_order
FROM (VALUES
  ('faith_values', 'How important is faith or religion in your life?', 1),
  ('faith_values', 'How often do you participate in faith-related activities (e.g., church, prayer, study)?', 2),
  ('faith_values', 'Would you date someone with very different religious beliefs from your own?', 3),
  ('faith_values', 'Do you prefer a partner who shares your faith practices?', 4),
  ('faith_values', 'Is personal integrity (keeping promises, telling the truth) a non-negotiable for you?', 5),
  ('relationship_intent', 'What relationship horizon are you seeking right now?', 1),
  ('relationship_intent', 'How quickly do you prefer a relationship to become exclusive?', 2),
  ('relationship_intent', 'How important is regular quality time (e.g., weekly date night)?', 3),
  ('relationship_intent', 'Would you relocate within the next 2 years for the right relationship?', 4),
  ('relationship_intent', 'How do you feel about long-distance relationships?', 5),
  ('kids_family', 'Do you want children?', 1),
  ('kids_family', 'If you want children, when would you ideally like to start?', 2),
  ('kids_family', 'How open are you to adoption or fostering?', 3),
  ('kids_family', 'How important is being close with extended family?', 4),
  ('kids_family', 'Should parenting roles be traditional, flexible, or fully shared?', 5),
  ('monogamy_boundaries', 'What relationship structure do you prefer?', 1),
  ('monogamy_boundaries', 'Is flirting with others while in a relationship acceptable?', 2),
  ('monogamy_boundaries', 'Are you comfortable with public displays of affection (PDA)?', 3),
  ('monogamy_boundaries', 'Is watching adult content while in a relationship acceptable?', 4),
  ('monogamy_boundaries', 'How important is sexual exclusivity?', 5),
  ('lifestyle_cleanliness', 'How tidy/organized do you prefer your home to be?', 1),
  ('lifestyle_cleanliness', 'How do you feel about pets in the home?', 2),
  ('lifestyle_cleanliness', 'Do you prefer early mornings or late nights as your routine?', 3),
  ('lifestyle_cleanliness', 'How often do you cook at home vs eat out?', 4),
  ('lifestyle_cleanliness', 'How important is regular exercise/fitness to you?', 5),
  ('substances', 'Do you drink alcohol?', 1),
  ('substances', 'Do you smoke cigarettes or vape?', 2),
  ('substances', 'What is your view on recreational cannabis?', 3),
  ('substances', 'What is your view on other recreational drugs?', 4),
  ('substances', 'How comfortable are you with your partner drinking socially without you?', 5),
  ('money_work', 'How would you describe your money habits?', 1),
  ('money_work', 'Do you keep a monthly budget or track spending?', 2),
  ('money_work', 'How important is career ambition in your life?', 3),
  ('money_work', 'How do you feel about splitting expenses with a partner?', 4),
  ('money_work', 'How do you feel about one partner pausing career for family needs?', 5),
  ('politics_tolerance', 'How important are politics in your day-to-day life?', 1),
  ('politics_tolerance', 'Could you be in a relationship with someone with very different political views?', 2),
  ('politics_tolerance', 'How comfortable are you discussing sensitive topics (religion/politics) with a partner?', 3),
  ('politics_tolerance', 'How important is community service or volunteering to you?', 4),
  ('politics_tolerance', 'Should partners share broadly similar moral/ethical views?', 5),
  ('conflict_communication', 'What is your default conflict style?', 1),
  ('conflict_communication', 'When upset, do you prefer space or immediate discussion?', 2),
  ('conflict_communication', 'How important is apologizing and making amends after conflict?', 3),
  ('conflict_communication', 'How often do you like to communicate during the day with a partner?', 4),
  ('conflict_communication', 'How do you feel about couples therapy or counseling if needed?', 5),
  ('time_ambition', 'How structured vs spontaneous do you prefer your week to be?', 1),
  ('time_ambition', 'How do you prefer to spend weekends?', 2),
  ('time_ambition', 'How important are personal goals/hobbies outside the relationship?', 3),
  ('time_ambition', 'Would you prioritize travel/adventure in the next 3 years?', 4),
  ('time_ambition', 'Are you comfortable with different social energy levels (introvert/extrovert) in a partner?', 5)
) AS q(category_key, text, sort_order)
JOIN c ON c.key = q.category_key;

WITH q AS (SELECT id, text FROM questions)
INSERT INTO question_answers (question_id, label, sort)
SELECT q.id, a.label, a.sort
FROM q JOIN (VALUES
  ('How important is faith or religion in your life?', 'Central to my life', 1),
  ('How important is faith or religion in your life?', 'Important but balanced', 2),
  ('How important is faith or religion in your life?', 'Cultural/occasional', 3),
  ('How important is faith or religion in your life?', 'Not important', 4),
  ('How often do you participate in faith-related activities (e.g., church, prayer, study)?', 'Weekly or more', 1),
  ('How often do you participate in faith-related activities (e.g., church, prayer, study)?', 'Monthly', 2),
  ('How often do you participate in faith-related activities (e.g., church, prayer, study)?', 'Few times a year', 3),
  ('How often do you participate in faith-related activities (e.g., church, prayer, study)?', 'Rarely/Never', 4),
  ('Would you date someone with very different religious beliefs from your own?', 'Yes', 1),
  ('Would you date someone with very different religious beliefs from your own?', 'Maybe/depends', 2),
  ('Would you date someone with very different religious beliefs from your own?', 'No', 3),
  ('Do you prefer a partner who shares your faith practices?', 'Prefer same practices', 1),
  ('Do you prefer a partner who shares your faith practices?', 'Open if values align', 2),
  ('Do you prefer a partner who shares your faith practices?', 'No preference', 3),
  ('Is personal integrity (keeping promises, telling the truth) a non-negotiable for you?', 'Yes, non-negotiable', 1),
  ('Is personal integrity (keeping promises, telling the truth) a non-negotiable for you?', 'Important but context matters', 2),
  ('Is personal integrity (keeping promises, telling the truth) a non-negotiable for you?', 'Not a strict requirement', 3),
  ('What relationship horizon are you seeking right now?', 'Marriage-minded (long-term)', 1),
  ('What relationship horizon are you seeking right now?', 'Long-term, see where it goes', 2),
  ('What relationship horizon are you seeking right now?', 'Short-term/casual', 3),
  ('What relationship horizon are you seeking right now?', 'Unsure', 4),
  ('How quickly do you prefer a relationship to become exclusive?', 'Within 1–3 months', 1),
  ('How quickly do you prefer a relationship to become exclusive?', 'Within 3–6 months', 2),
  ('How quickly do you prefer a relationship to become exclusive?', 'After 6+ months', 3),
  ('How quickly do you prefer a relationship to become exclusive?', 'When it feels right (no timeline)', 4),
  ('How important is regular quality time (e.g., weekly date night)?', 'Very important', 1),
  ('How important is regular quality time (e.g., weekly date night)?', 'Somewhat important', 2),
  ('How important is regular quality time (e.g., weekly date night)?', 'Nice but optional', 3),
  ('How important is regular quality time (e.g., weekly date night)?', 'Not important', 4),
  ('Would you relocate within the next 2 years for the right relationship?', 'Yes', 1),
  ('Would you relocate within the next 2 years for the right relationship?', 'Maybe/depends', 2),
  ('Would you relocate within the next 2 years for the right relationship?', 'No', 3),
  ('How do you feel about long-distance relationships?', 'Open to it', 1),
  ('How do you feel about long-distance relationships?', 'Maybe short-term only', 2),
  ('How do you feel about long-distance relationships?', 'Not for me', 3),
  ('Do you want children?', 'Yes', 1),
  ('Do you want children?', 'Maybe/unsure', 2),
  ('Do you want children?', 'No', 3),
  ('If you want children, when would you ideally like to start?', 'Within 1–2 years', 1),
  ('If you want children, when would you ideally like to start?', 'In 3–5 years', 2),
  ('If you want children, when would you ideally like to start?', '5+ years', 3),
  ('If you want children, when would you ideally like to start?', 'No preference/unsure', 4),
  ('How open are you to adoption or fostering?', 'Very open', 1),
  ('How open are you to adoption or fostering?', 'Somewhat open', 2),
  ('How open are you to adoption or fostering?', 'Prefer biological only', 3),
  ('How important is being close with extended family?', 'Very important', 1),
  ('How important is being close with extended family?', 'Somewhat important', 2),
  ('How important is being close with extended family?', 'Not important', 3),
  ('Should parenting roles be traditional, flexible, or fully shared?', 'Traditional roles', 1),
  ('Should parenting roles be traditional, flexible, or fully shared?', 'Flexible by season', 2),
  ('Should parenting roles be traditional, flexible, or fully shared?', 'Fully shared/egalitarian', 3),
  ('What relationship structure do you prefer?', 'Monogamy', 1),
  ('What relationship structure do you prefer?', 'Monogamish/mostly monogamy', 2),
  ('What relationship structure do you prefer?', 'Open/consensual non-monogamy', 3),
  ('Is flirting with others while in a relationship acceptable?', 'Not acceptable', 1),
  ('Is flirting with others while in a relationship acceptable?', 'Mild/harmless flirting is okay', 2),
  ('Is flirting with others while in a relationship acceptable?', 'Acceptable', 3),
  ('Are you comfortable with public displays of affection (PDA)?', 'Comfortable', 1),
  ('Are you comfortable with public displays of affection (PDA)?', 'A little is okay', 2),
  ('Are you comfortable with public displays of affection (PDA)?', 'Prefer private affection', 3),
  ('Is watching adult content while in a relationship acceptable?', 'Acceptable', 1),
  ('Is watching adult content while in a relationship acceptable?', 'Acceptable with boundaries', 2),
  ('Is watching adult content while in a relationship acceptable?', 'Not acceptable', 3),
  ('How important is sexual exclusivity?', 'Mandatory', 1),
  ('How important is sexual exclusivity?', 'Very important', 2),
  ('How important is sexual exclusivity?', 'Not very important', 3),
  ('How tidy/organized do you prefer your home to be?', 'Very tidy (minimal clutter)', 1),
  ('How tidy/organized do you prefer your home to be?', 'Moderately tidy', 2),
  ('How tidy/organized do you prefer your home to be?', 'Casual/messy is fine', 3),
  ('How do you feel about pets in the home?', 'Love pets (want them around)', 1),
  ('How do you feel about pets in the home?', 'Okay with pets', 2),
  ('How do you feel about pets in the home?', 'Prefer no pets', 3),
  ('Do you prefer early mornings or late nights as your routine?', 'Early mornings', 1),
  ('Do you prefer early mornings or late nights as your routine?', 'Flexible/depends', 2),
  ('Do you prefer early mornings or late nights as your routine?', 'Late nights', 3),
  ('How often do you cook at home vs eat out?', 'Mostly cook at home', 1),
  ('How often do you cook at home vs eat out?', 'Balanced mix', 2),
  ('How often do you cook at home vs eat out?', 'Mostly eat out', 3),
  ('How important is regular exercise/fitness to you?', 'Very important', 1),
  ('How important is regular exercise/fitness to you?', 'Somewhat important', 2),
  ('How important is regular exercise/fitness to you?', 'Not important', 3),
  ('Do you drink alcohol?', 'No', 1),
  ('Do you drink alcohol?', 'Occasionally/socially', 2),
  ('Do you drink alcohol?', 'Regularly', 3),
  ('Do you smoke cigarettes or vape?', 'No', 1),
  ('Do you smoke cigarettes or vape?', 'Occasionally', 2),
  ('Do you smoke cigarettes or vape?', 'Yes', 3),
  ('What is your view on recreational cannabis?', 'Prefer not at all', 1),
  ('What is your view on recreational cannabis?', 'Okay occasionally', 2),
  ('What is your view on recreational cannabis?', 'Comfortable/regular', 3),
  ('What is your view on other recreational drugs?', 'Not acceptable', 1),
  ('What is your view on other recreational drugs?', 'Case-by-case/rare use', 2),
  ('What is your view on other recreational drugs?', 'Acceptable', 3),
  ('How comfortable are you with your partner drinking socially without you?', 'Comfortable', 1),
  ('How comfortable are you with your partner drinking socially without you?', 'Prefer moderation/notice', 2),
  ('How comfortable are you with your partner drinking socially without you?', 'Uncomfortable', 3),
  ('How would you describe your money habits?', 'Saver / cautious', 1),
  ('How would you describe your money habits?', 'Balanced', 2),
  ('How would you describe your money habits?', 'Spender / free-flowing', 3),
  ('Do you keep a monthly budget or track spending?', 'Yes, consistently', 1),
  ('Do you keep a monthly budget or track spending?', 'Sometimes', 2),
  ('Do you keep a monthly budget or track spending?', 'No', 3),
  ('How important is career ambition in your life?', 'Very important', 1),
  ('How important is career ambition in your life?', 'Somewhat important', 2),
  ('How important is career ambition in your life?', 'Not important', 3),
  ('How do you feel about splitting expenses with a partner?', 'Roughly 50/50', 1),
  ('How do you feel about splitting expenses with a partner?', 'Proportional to income', 2),
  ('How do you feel about splitting expenses with a partner?', 'One person pays more/most', 3),
  ('How do you feel about one partner pausing career for family needs?', 'Supportive/open to it', 1),
  ('How do you feel about one partner pausing career for family needs?', 'Maybe/depends on season', 2),
  ('How do you feel about one partner pausing career for family needs?', 'Prefer not', 3),
  ('How important are politics in your day-to-day life?', 'Very important', 1),
  ('How important are politics in your day-to-day life?', 'Somewhat important', 2),
  ('How important are politics in your day-to-day life?', 'Not important', 3),
  ('Could you be in a relationship with someone with very different political views?', 'Yes', 1),
  ('Could you be in a relationship with someone with very different political views?', 'Maybe/depends', 2),
  ('Could you be in a relationship with someone with very different political views?', 'No', 3),
  ('How comfortable are you discussing sensitive topics (religion/politics) with a partner?', 'Very comfortable', 1),
  ('How comfortable are you discussing sensitive topics (religion/politics) with a partner?', 'Somewhat comfortable', 2),
  ('How comfortable are you discussing sensitive topics (religion/politics) with a partner?', 'Prefer to avoid', 3),
  ('How important is community service or volunteering to you?', 'Very important', 1),
  ('How important is community service or volunteering to you?', 'Somewhat important', 2),
  ('How important is community service or volunteering to you?', 'Not important', 3),
  ('Should partners share broadly similar moral/ethical views?', 'Yes', 1),
  ('Should partners share broadly similar moral/ethical views?', 'Some alignment is enough', 2),
  ('Should partners share broadly similar moral/ethical views?', 'No, differences are fine', 3),
  ('What is your default conflict style?', 'Direct (address it now)', 1),
  ('What is your default conflict style?', 'Collaborative (work it out)', 2),
  ('What is your default conflict style?', 'Avoidant (cool off first)', 3),
  ('When upset, do you prefer space or immediate discussion?', 'Space first', 1),
  ('When upset, do you prefer space or immediate discussion?', 'Discuss soon', 2),
  ('When upset, do you prefer space or immediate discussion?', 'Discuss immediately', 3),
  ('How important is apologizing and making amends after conflict?', 'Very important', 1),
  ('How important is apologizing and making amends after conflict?', 'Somewhat important', 2),
  ('How important is apologizing and making amends after conflict?', 'Not important', 3),
  ('How often do you like to communicate during the day with a partner?', 'Often (many check-ins)', 1),
  ('How often do you like to communicate during the day with a partner?', 'Moderate (1–2 check-ins)', 2),
  ('How often do you like to communicate during the day with a partner?', 'Low (evening recap)', 3),
  ('How do you feel about couples therapy or counseling if needed?', 'Open/positive', 1),
  ('How do you feel about couples therapy or counseling if needed?', 'Neutral/depends', 2),
  ('How do you feel about couples therapy or counseling if needed?', 'Prefer not', 3),
  ('How structured vs spontaneous do you prefer your week to be?', 'Highly structured', 1),
  ('How structured vs spontaneous do you prefer your week to be?', 'Balanced', 2),
  ('How structured vs spontaneous do you prefer your week to be?', 'Very spontaneous', 3),
  ('How do you prefer to spend weekends?', 'Mostly out & social', 1),
  ('How do you prefer to spend weekends?', 'Mix of out & in', 2),
  ('How do you prefer to spend weekends?', 'Mostly in / low-key', 3),
  ('How important are personal goals/hobbies outside the relationship?', 'Very important', 1),
  ('How important are personal goals/hobbies outside the relationship?', 'Somewhat important', 2),
  ('How important are personal goals/hobbies outside the relationship?', 'Not important', 3),
  ('Would you prioritize travel/adventure in the next 3 years?', 'Yes', 1),
  ('Would you prioritize travel/adventure in the next 3 years?', 'Maybe/depends', 2),
  ('Would you prioritize travel/adventure in the next 3 years?', 'No', 3),
  ('Are you comfortable with different social energy levels (introvert/extrovert) in a partner?', 'Yes', 1),
  ('Are you comfortable with different social energy levels (introvert/extrovert) in a partner?', 'Maybe/depends', 2),
  ('Are you comfortable with different social energy levels (introvert/extrovert) in a partner?', 'Prefer similar energy', 3)
) AS a(text, label, sort) ON q.text = a.text;
